### ISSUE TITLE
Entities Configuration

### ISSUE THREAD

**Issue by milandzuris** [andrew-codechimp/HA-Battery-Notes#1127]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/andrew-codechimp/ha-battery-notes/issues?q=is%3Aissue+label%3Aenhancement).

### Is your feature request related to a problem? Please describe.

Hi, please add Configuration for Entites, i only need Battery Last Replaced and Button, i dont need other entities

### Describe the solution you'd like

*

### Describe alternatives you've considered

*

### Additional context

*

**Comment by andrew-codechimp** [comment]
Battery+ is an integral part of monitoring the battery replaced and I am unable to split this up without causing a huge amount of spaghetti code which I want to avoid.
