### ISSUE TITLE
Possibility to indicate the rechargeability

### ISSUE THREAD

**Issue by 4D4M-Github** [andrew-codechimp/HA-Battery-Notes#114]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/andrew-codechimp/ha-battery-notes/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement).

### Is your feature request related to a problem? Please describe.

I use a mix of rechargeable and disposable batteries, and although I can usually tell which one I'm using by the instantaneous voltage, it would be handy if this could be included in the integration.

### Describe the solution you'd like

There could be an attribute in the integration item that could be checked to indicate that the device currently has a battery that can be charged (e.g. CR2450/LIR2450, CR2032/ML2032 etc.)

### Describe alternatives you've considered

I can also imagine a way to have multiple optional batteries associated with a given type of device, but that would probably require a more labour-intensive or more sofisticated solution at the moment.

### Additional context

I may be the only one in the world who has a problem with using disposable (albeit less self-discharging) batteries, so I'd be happy to have someone to partner with me on the idea (:

**Comment by andrew-codechimp** [comment]
Where I use rechargeable batteries I suffix an (r) on the end of the note to remind me e.g. 2x AA(r).  Not sure how this could be done automatically.

**Comment by 4D4M-Github** [comment]
It hadn't occurred to me that this should be automated, although the initial voltage makes it obvious in general. I was only thinking of a manual switch, but I can live with your solution.

**Comment by andrew-codechimp** [comment]
I'll close this for now, I don't want to introduce too much clutter against a device but will always revisit if I can find good reasons to do so.

**Comment by remidebette** [comment]
Hi,
The voltage of non alkaline batteries are usually indicated as low, it would be nice to be able to indicate which devices have non alkaline batteries and the charge level would be automatically adapted.

Is there already an issue for that?

**Comment by andrew-codechimp** [comment]
If you are using a template to determine the low you can adjust the voltage at which it goes low.
