### ISSUE TITLE
Repeat low battery event firing based on threshold

### ISSUE THREAD

**Issue by uvjim** [andrew-codechimp/HA-Battery-Notes#1185]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/andrew-codechimp/ha-battery-notes/issues?q=is%3Aissue+label%3Aenhancement).

### Is your feature request related to a problem? Please describe.

I currently use an automation that is triggered on every state change, and filtered for only batteries, to send a notification when a battery is low (I made this before using HA Battery). The automation allows setting a threshold so that it repeatedly sends a notification if it falls by a percentage. As an example my low threshold (again not managed by HA battery at the moment) is 30%. I would get a notification when any battery falls to 30% or below. Then, I have a helper that says if the battery has fallen by another x% the notification would be sent again.

### Describe the solution you'd like

The ability to globally (or potentially per device configuration) set a threshold that would cause the battery low event to fire again. The payload should include e ought information to identify the entity in question so that information can be retrieved and use din the notification (I wouldn't mind if I had to Jinja template that for the notification). The event should not be fired if the battery is being charged, i.e. the state has increased but is still below the low threshold.

### Describe alternatives you've considered

See the description for what I already have configured.

### Additional context

This would actually as a nag reminder to change the battery.

**Comment by andrew-codechimp** [comment]
Interesting idea, I'd also potentially think about a service to fire events for all low batteries again to maybe use as a weekly reminder or the like.
I'll give it some thought.

**Comment by andrew-codechimp** [comment]
This is now in beta 2.2.x
I went with a new service to kick off reminders as documented [here](https://andrew-codechimp.github.io/HA-Battery-Notes/services/#battery_notescheck_battery_low) 
I couldn't easily get a detection of increase, it would require storing/resetting low levels which would be a fair bit of work, will see how often this causes issues.

**Comment by uvjim** [comment]
@andrew-codechimp - thanks. I'll need to have a look and see how to get it all to hang together for my use case of nagging.

**Comment by uvjim** [comment]
@andrew-codechimp - I pretty much have this working now. However, I've had to take a couple of things into account: -

* the service is called every 5 minutes and correctly fires an event for a battery that is low. However, `reminder` is set to `true` because it was initiated from the service even though it was already below the threshold and I'd never been notified previously (think HA starting up after battery had gone low, or battery only being shadowed by the integration after it being low). To cope with this, I keep a track, using a helper, of which devices I'd previously been told about. Once the battery goes above the threshold, it's record is removed from the helper.
* the previous battery level and current battery level could be equal so I have to check for that and not remind again. This isn't a problem because use cases could require a reminder even if the battery level hasn't changed.

I'll keep testing, but I think it's doing the job without the automation triggering on every state change - makes it easier to troubleshoot using "Traces" on a potentially busy system. The added delay of triggering every 5 minutes is negligible against every state change - the urgency of knowing the battery is low or being reminded about it is not really that high.

**Comment by andrew-codechimp** [comment]
Glad you spotted the reminder data, I thought that would be useful to know how the event was fired.  As you say HA restarts/adding a device when it's already low will all mess with the original events unfortunately.
My urgency on reminder is weekly so I use a schedule helper rather than a timer but then my typical devices don't drop that quickly.

Glad it seems to be working, always open to discuss more if you think how I could add anything else to help here, as long as I can balance it with being easy for most to understand and not getting in the way.

**Comment by uvjim** [comment]
Just did a bit more testing and realised (after fixing a logic error in my automation) that whilst the event doesn't fire when adding a battery that is already low; it does fire when the service checks. Would this make it possible to run the same check and fire the event when creating the battery+ entity?

It's only a thought, and not a big deal for me because my check is currently set to every 5 minutes (only whilst testing, I'll be pushing that out slightly when finished), but it would ensure that `reminder` being set to `true` with the service would be correct in one more scenario (`reminder` would be `false` when checked at create time).

**Comment by uvjim** [comment]
Understood. I wonder then if `reminder` is the wrong term. Maybe something like `initiator` which could then be set to either `service` or `bau` (or whatever values make more sense). This way you can check why the event was fired. Essentially it isn't a reminder for a low battery unless you'd previously told someone about the low battery. Identifying the source that initiated the event removes that potential.

**Comment by andrew-codechimp** [comment]
I did struggle with that decision, I wanted a bool rather than a magic string to make it easy to approach for the majority of users.
A config setting of "resend low events on start" with reminder set to false is another option I've thought about to allow both list fillers and notifiers to work.

**Comment by uvjim** [comment]
It's a toughy. It doesn't affect me as I'm tracking the devices that I've been notified about so I don't need to use that field now.

I think everything seems to be working as expected now, so I can probably disable my other automation and stick with the new one which is substantially easier to manage.

Thanks again for the work.

**Comment by andrew-codechimp** [comment]
No problem, it's always good to discuss these things to try and find ways to get the functionality people want, I've learnt a lot over the past few months with some really interesting use cases and changed how I've been managing things myself because of it.
