### ISSUE TITLE
Library update failed

### ISSUE THREAD

**Issue by holdestmade** [andrew-codechimp/HA-Battery-Notes#1224]
## System Information

version | core-2024.3.0b5
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.2
os_name | Linux
os_version | 6.6.16-haos
arch | aarch64
timezone | Europe/London
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4993
Installed Version | 1.34.0
Stage | running
Available Repositories | 1476
Downloaded Repositories | 48
HACS Data | ok

</details>

<details><summary>AccuWeather</summary>

can_reach_server | ok
-- | --
remaining_requests | 45

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 23 March 2024 at 12:00 am
relayer_connected | true
relayer_region | eu-central-1
remote_enabled | false
remote_connected | false
alexa_enabled | true
google_enabled | false
remote_server | eu-xxxxxxxxxxxxxxxxxxx
certificate_status | ready
instance_id | xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 12.0
-- | --
update_channel | beta
supervisor_version | supervisor-2024.02.1
agent_version | 1.6.0
docker_version | 24.0.7
disk_total | 56.6 GB
disk_used | 42.3 GB
healthy | true
supported | true
board | odroid-n2
supervisor_api | ok
version_api | ok
installed_addons | Samba share (12.3.0), Home Assistant Google Drive Backup (0.105.2), Terminal & SSH (9.9.0), Z-Wave JS UI (3.4.0), Mosquitto broker (6.4.0), Zigbee2MQTT (1.35.3-1), go2rtc (1.8.5), GivTCP (2.4.3), OpenSpeedTest (v2.0.3), ESPHome (2024.2.1), Studio Code Server (5.15.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 7
-- | --
resources | 25
error | /config/ui-lovelace.yaml not found
views | 34
mode | yaml

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 26 February 2024 at 4:58 pm
-- | --
current_recorder_run | 4 March 2024 at 3:23 pm
estimated_db_size | 2166.59 MiB
database_engine | sqlite
database_version | 3.44.2

</details>

<details><summary>Solcast PV Forecast</summary>

can_reach_server | ok
-- | --
used_requests | 0
rooftop_site_count | 2

</details>

### Checklist

- [X] I have added `battery_notes:` to my configuration.yaml and restarted.
- [X] I have read the [FAQ's](https://andrew-codechimp.github.io/HA-Battery-Notes/faq).
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/andrew-codechimp/ha-battery-notes/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Error on restart

Library update failed, this could be a GitHub or internet connectivity issue, will retry later.

### Reproduction steps

1. Restart
2.
3.
...

### Debug logs

```text
This error originated from a custom integration.

Logger: custom_components.battery_notes.library_updater
Source: custom_components/battery_notes/library_updater.py:102
integration: Battery Notes (documentation, issues)
First occurred: 3:24:08 pm (1 occurrences)
Last logged: 3:24:08 pm

Library update failed, this could be a GitHub or internet connectivity issue, will retry later.
```

### Diagnostics dump

NA

**Comment by andrew-codechimp** [comment]
As indicated this could just be a temporary issue at GitHub or with your internet, as it's just one occurrence it'll probably work later.  
If you see multiple issues logged then that could be more serious but I'm not seeing issues when mine updates. 
It doesn't stop functionality, just won't get the latest device details for discovering new things.

**Comment by holdestmade** [comment]
Ah right, ok, I updated to HA beta and this started so thought it was related to that. I'll keep an eye on it

**Comment by andrew-codechimp** [comment]
Closing this issue, if it occurs repeatedly then please re-open.

**Comment by artt652** [comment]
Same issue, appears immediately  after HA restart.

*Home Assistant*

Installation method: Home Assistant OS
Core: 2025.6.3
Supervisor: 2025.06.2
Operating System: 16.0.rc1
Frontend: 20250531.4


```
This error occurred in a custom integration.

Logger: custom_components.battery_notes.library_updater
Source: custom_components/battery_notes/library_updater.py:115
Integration: Battery Notes (documentation, issues)
First recorded: 02:00:14 (1 occurrence)
Last recorded: 02:00:14

Unable to update library, will retry later.
```

**Comment by andrew-codechimp** [comment]
At HA restart it tries to pull any changes from a storage bucket, if there's any internet outage stopping that then you'll get this.
The library is cached so just means you won't get the very latest device library until it retries.

**Comment by artt652** [comment]
Yes you are absolutely right, but I propose to add some delay prior to first update attempt after restart to prevent raise Homeassistant error,  it not suppose to be apprear

**Comment by andrew-codechimp** [comment]
Yes, that would be a nice improvement, I'll look into it for a future release.

**Comment by artt652** [comment]
Appreciate for your support!
