### ISSUE TITLE
Add support for battery powered Bluetooth devices

### ISSUE THREAD

**Issue by bekesizl** [andrew-codechimp/HA-Battery-Notes#124]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/andrew-codechimp/ha-battery-notes/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement).

### Is your feature request related to a problem? Please describe.

I have battery powered two Bluetooth sensors.
I would like to have them auto configured, but I don't know what data to enter to the database.

### Describe the solution you'd like

I would like to be able to add data for Bluetooth devices to the database and have them auto recognised.

### Describe alternatives you've considered

What other data can I add to support my case?

### Additional context

https://kb.shelly.cloud/knowledge-base/shellyblu-door-window

https://kb.shelly.cloud/knowledge-base/shellyblu-motion

**Comment by andrew-codechimp** [comment]
Bluetooth devices can be added today and if in the library will be discovered, if they aren't in the library just go into Settings -> Integrations -> Battery Notes screen add a new device where you can enter the battery details manually.

If you want to add to the library, just copy the manufacturer/model from the device info and create a pull request as detailed in the readme.

**Comment by bekesizl** [comment]
OK. Then I ask otherwise.
Those two sensors are using the BTHome integration.
The information displayed doesn't match, what is displayed in your documentation. Maybe it is not even possible to add information for automatic configuration at the moment for such devices.
I added the information manually anyway.
![image](https://github.com/andrew-codechimp/HA-Battery-Notes/assets/41523450/511173a5-a2ec-4fdf-b2da-e736ad71946b)
![image](https://github.com/andrew-codechimp/HA-Battery-Notes/assets/41523450/5c1e4e40-0395-45db-a25f-5db26662b0a2)

**Comment by andrew-codechimp** [comment]
I've not seen bluetooth devices showing like this and I don't have any to test.
You are right, they will have to be added manually.
