### ISSUE TITLE
Documentation Link Broken

### ISSUE THREAD

**Issue by uvjim** [andrew-codechimp/HA-Battery-Notes#1241]
### System Health details

N/A

### Checklist

- [X] I have added `battery_notes:` to my configuration.yaml and restarted.
- [X] I have read the [FAQ's](https://andrew-codechimp.github.io/HA-Battery-Notes/faq).
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/andrew-codechimp/ha-battery-notes/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

The highlighted link in the image goes to a 404 page.

![image](https://github.com/andrew-codechimp/HA-Battery-Notes/assets/8431065/1848b465-6587-4b58-ad13-153a543efc82)

### Reproduction steps

Click the link.

**Comment by andrew-codechimp** [comment]
Thanks, fixed now but you'll probably need to clear/reload the page in your browser to get the latest version immediately.

**Comment by uvjim** [comment]
Confirmed fixed. Thanks for the quick responses.
