### ISSUE TITLE
Doubt this is a bug it's really user error

### ISSUE THREAD

**Issue by the5evansfamily** [andrew-codechimp/HA-Battery-Notes#126]
### System Health details

N/A

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/andrew-codechimp/ha-battery-notes/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Have installed via HACS and added to configuration .yaml the battery_notes: and did the restart. It's not being up the SmartThings sensors that I think are already in the database. So I have something off just asking for ideas

### Reproduction steps

1. N/A
2.
3.
...

### Debug logs

```text
n/a
```

### Diagnostics dump

N/A

**Comment by andrew-codechimp** [comment]
It is most probably that the integration you are using, ZHA or Z2M for example have the manufacturer or model slightly different from what's in the library.
You can always add the devices manually by going into Settings -> Integrations -> Battery Notes screen add a new device where you can enter the battery details manually.
If you're comfortable with editing json and doing GitHub pull requests then you can add it to the library.
