### ISSUE TITLE
Missing service - battery_notes.check_battery_low

### ISSUE THREAD

**Issue by adam-cobb** [andrew-codechimp/HA-Battery-Notes#1260]
## System Information

version | core-2024.2.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.1
os_name | Linux
os_version | 6.1.59
arch | x86_64
timezone | Europe/London
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.34.0
Stage | running
Available Repositories | 1405
Downloaded Repositories | 29

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 11.1
-- | --
update_channel | stable
supervisor_version | supervisor-2024.02.1
agent_version | 1.6.0
docker_version | 24.0.6
disk_total | 62.3 GB
disk_used | 30.7 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | AdGuard Home (5.0.3), Samba share (12.3.0), Terminal & SSH (9.9.0), Samba Backup (5.2.0), RTSP Simple Server Add-on (v0.17.6), Duck DNS (1.15.0), File editor (5.8.0), Mosquitto broker (6.4.0), Crowdsec (1.6.0), Crowdsec Firewall Bouncer (v0.0.28), TheengsGateway (1.11.0), Piper (1.5.0), Whisper (1.0.2), eufy-security-ws (1.7.1), Cloudflared (5.1.5), Studio Code Server (5.15.0), Govee to MQTT Bridge (2024.01.24-ea3cd430)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 12
views | 9
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | March 3, 2024 at 2:01 AM
-- | --
current_recorder_run | March 6, 2024 at 11:58 AM
estimated_db_size | 766.09 MiB
database_engine | sqlite
database_version | 3.44.2

</details>

### Checklist

- [X] I have added `battery_notes:` to my configuration.yaml and restarted.
- [X] I have read the [FAQ's](https://andrew-codechimp.github.io/HA-Battery-Notes/faq).
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/andrew-codechimp/ha-battery-notes/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

I'm not sure if i'm missing something but the service battery_notes.check_battery_low does not exist in my installation - I only see the check_battrery_last_reported and set_battery replaced services available.

### Reproduction steps

Attempted to set up automation using examples to notify on low battery but the service is not available

**Comment by andrew-codechimp** [comment]
That service is brand new and was only in beta this week, I don't have versioned docs unfortunately.  
I've just released it now so if you update via hacs you should get it.
