### ISSUE TITLE
Feature to edit battery threshold on global scale for all items

### ISSUE THREAD

**Issue by xelemorf** [andrew-codechimp/HA-Battery-Notes#1265]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/andrew-codechimp/ha-battery-notes/issues?q=is%3Aissue+label%3Aenhancement).

### Is your feature request related to a problem? Please describe.

When I'm about to finetune battery thresholds I need to amend all of the thresholds for my devices. This can be cumbersome when working with 130 devices.

### Describe the solution you'd like

If thre would be a settting which could set the thresholds globally for all configured devices, that would be great. Even better would be if we could select which devices should have what kind of thresholds in a bulk fashion.

### Describe alternatives you've considered

Manually iterating through 130 devices makes me reconsider my life choices and the overall meaning of life. :D

### Additional context

Btw, appreciate your work, thank you.

**Comment by andrew-codechimp** [comment]
There is a default global threshold already via [config settings](https://andrew-codechimp.github.io/HA-Battery-Notes/configuration/), as long as you leave each device at zero it will use this value.
