### ISSUE TITLE
Adjust the battery types in Zooz ZSE42 and ZSE44

### ISSUE THREAD

**Issue by hollec** [andrew-codechimp/HA-Battery-Notes#1266]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/andrew-codechimp/ha-battery-notes/issues?q=is%3Aissue+label%3Aenhancement).

### Is your feature request related to a problem? Please describe.

The update in #1228 accidentally modified the wrong device. I added in a new ZSE44 (2.0 with 800 Series Z-Wave) to HA today and the hardware retains the CR2450 as in the previous library regardless of hardware revision.

### Describe the solution you'd like

- model ZSE44 should retain the original "battery_type": "CR2450"
- model ZSE42 should swap to "battery_type": "MANUAL" per the discussion on multiple batteries for the same model under #1228

### Describe alternatives you've considered

I can manually set the battery type for the ZSE44.

### Additional context

ZSE42 with different batteries: https://www.support.getzooz.com/kb/article/1630-what-s-the-difference-between-the-zse42-700-series-and-the-zse42-800lr-800-series/
ZSE44: https://www.support.getzooz.com/kb/article/912-zse44-temperature-humidity-xs-sensor-change-log/

**Comment by andrew-codechimp** [comment]
Thanks for the clarification, this has now been changed.
