### ISSUE TITLE
Match device model via regex/substring

### ISSUE THREAD

**Issue by AlexxIT** [andrew-codechimp/HA-Battery-Notes#1280]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/andrew-codechimp/ha-battery-notes/issues?q=is%3Aissue+label%3Aenhancement).

### Is your feature request related to a problem? Please describe.

I'm developer of integration with a lot of battery devices:
https://github.com/andrew-codechimp/HA-Battery-Notes/issues/472

I'm thinking about changing model name template. For example:
- from `zigbee WSDCGQ01LM (lumi.sensor_ht)` to `Zigbee: WSDCGQ01LM, lumi.sensor_ht`
- from `ble CGD1` to `BLE: CGD1, cgllc.clock.dove`

So all your matching will be broken. Also library has a lot of duplicates:
```json5
        {
            "manufacturer": "Xiaomi",
            "model": "MiJia temperature & humidity sensor (WSDCGQ01LM)",
            "battery_type": "CR2032"
        },
        {
            "manufacturer": "Xiaomi",
            "model": "WSDCGQ01LM",
            "battery_type": "CR2032"
        }
        {
            "manufacturer": "Xiaomi",
            "model": "zigbee WSDCGQ01LM (lumi.sensor_ht)",
            "battery_type": "CR2032"
        }
```

### Describe the solution you'd like

I think in some cases will be enough by matching only market model (`re.match(r"\bWSDCGQ01LM\b")` inside model string.

### Describe alternatives you've considered

-

### Additional context

-

**Comment by andrew-codechimp** [comment]
Thanks for the context, a regex in these situations seems useful, I'll just have to think about any impacts but will add it to my list.

**Comment by andrew-codechimp** [comment]
As there has been very few scenarios where this will prove useful it's too much overhead/testing where a few duplicate entries would not cause issues so closing this.
