### ISSUE TITLE
Tuya devices not shown (Using smartlife integration)

### ISSUE THREAD

**Issue by YogevBokobza** [andrew-codechimp/HA-Battery-Notes#1289]
## System Information

version | core-2024.1.6
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.6
os_name | Linux
os_version | 6.1.74-haos
arch | x86_64
timezone | Asia/Jerusalem
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4465
Installed Version | 1.34.0
Stage | running
Available Repositories | 1476
Downloaded Repositories | 43

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | January 1, 2018 at 02:00
relayer_connected | false
relayer_region | null
remote_enabled | true
remote_connected | false
alexa_enabled | false
google_enabled | false
remote_server | null
certificate_status | null
instance_id | ba1d7b4958584b77a048a3f3a79597bb
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 11.5
-- | --
update_channel | stable
supervisor_version | supervisor-2024.02.1
agent_version | 1.6.0
docker_version | 24.0.7
disk_total | 30.8 GB
disk_used | 13.5 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Home Assistant Google Drive Backup (0.112.1), Advanced SSH & Web Terminal (17.2.0), Samba share (12.3.1), Duck DNS (1.15.0), PS5 MQTT (1.3.3), Studio Code Server (5.15.0), ESPHome (2024.2.2)

</details>

<details><summary>Dashboards</summary>

dashboards | 5
-- | --
resources | 25
views | 20
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | March 11, 2024 at 17:07
-- | --
current_recorder_run | March 12, 2024 at 15:57
estimated_db_size | 358.10 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

### Checklist

- [X] I have added `battery_notes:` to my configuration.yaml and restarted.
- [X] I have read the [FAQ's](https://andrew-codechimp.github.io/HA-Battery-Notes/faq).
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/andrew-codechimp/ha-battery-notes/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Hey,
I am using Tuya devices using "smartlife" integration (As Tuya integration stopped working).
I cannot see my T&H devices in the list and not shown in the discovery.
The device I have is matching to this: https://github.com/andrew-codechimp/HA-Battery-Notes/blob/main/custom_components/battery_notes/data/library.json#L3860-L3864 but still dont work.

Please help.

### Reproduction steps

1. Added and installed this integration
2. I added to the configuration file the line needed.
3. I saw some of my devices on the discovery but not Tuya once

**Comment by andrew-codechimp** [comment]
I don't have Tuya devices so can't test this.

Can you add the show_all_devices to your configuration, restart and try adding the battery note manually, it should appear on the list as long as it is a device, not individual entities without a device.

```
 battery_notes:
  show_all_devices: true
```
