### ISSUE TITLE
Addition of various devices

### ISSUE THREAD

**Issue by BRSS73** [andrew-codechimp/HA-Battery-Notes#135]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/andrew-codechimp/ha-battery-notes/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement).

### Is your feature request related to a problem? Please describe.

From Ikea and Ring

### Describe the solution you'd like

        {
            "manufacturer": "IKEA",
            "model": "FYRTUR roller blind (E1757)",
            "battery_type": "Rechargeable"
        },	        
        {
            "manufacturer": "Ring",
            "model": "Contact Sensor",
            "battery_type": "CR2032",
            "battery_quantity": 2
        },
	{
            "manufacturer": "Ring",
            "model": "Motion Sensor",
            "battery_type": "AA",
            "battery_quantity": 2
        },
	{
            "manufacturer": "Ring",
            "model": "Security Keypad",
            "battery_type": "Rechargeable"
        },

### Describe alternatives you've considered

-

### Additional context

-

**Comment by andrew-codechimp** [comment]
Thanks I've just added these
