### ISSUE TITLE
A universal toggle for what entities battery notes creates

### ISSUE THREAD

**Issue by PartyingChair** [andrew-codechimp/HA-Battery-Notes#1390]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/andrew-codechimp/ha-battery-notes/issues?q=is%3Aissue+label%3Aenhancement).

### Is your feature request related to a problem? Please describe.

I have an automation tigger at 9pm to tell me what batteries are low. When 1 is low, I get a notification listing 3 devices. One for the default battery entity for the device, 1 for the “battery low” sensor battery notes adds, and a third for “battery+” that battery notes adds. 

### Describe the solution you'd like

I’d like a universal toggle for all battery notes devices to say “I don’t need battery low, or battery+ on any devices” 

I like battery notes for the fact it tells me the battery type, and I can keep track easily of how often I’m replacing batteries. I don’t personally need multiple entities telling me the same thing 

### Describe alternatives you've considered

Ive disabled some of the entities by hand. This works, but as I expand my smart home and add more and more battery devices, it gets harder and harder to keep track of which devices I’ve disabled the entities on. A universal toggle for the integration would help make it easier to keep track of. 

### Additional context

I think I’ve added everything up above, I’m not sure I have anything else to add.

**Comment by andrew-codechimp** [comment]
Can I suggest you look at the events available and re-work your automations to use these, there's examples [here](https://andrew-codechimp.github.io/HA-Battery-Notes/community/)

Battery+ is the key to driving a lot of the services/events and disabling it would have a lot of knock on effects so I won't be able to add this option.

**Comment by PartyingChair** [comment]
But I don’t use those events/services. Maybe lots do, but probably not everyone. I don’t see why that prevents a universal toggle with a warning that explains it might cause issues with events/services. 

I tried those automations in the link and none worked to replace what I have. 


I’ll try to find another solution I guess. Thanks.
