### ISSUE TITLE
[not really a bug] Develco and Frient A/S products

### ISSUE THREAD

**Issue by ChristophCaina** [andrew-codechimp/HA-Battery-Notes#144]
### System Health details

Hi,
I own a frient A/S heat detector with Siren - Model: HESZB-120
I would like to add this device to the library.json file - but I noticed the following:

```
        {
            "manufacturer": "Develco",
            "model": "Smoke detector with siren (SMSZB-120)",
            "battery_type": "CR123"
        },
        {
            "manufacturer": "Develco Products A/S",
            "model": "AQSZB-110",
            "battery_type": "AA",
            "battery_quantity": 2
        },
        {
            "manufacturer": "frient",
            "model": "MOSZB-140",
            "battery_type": "AA",
            "battery_quantity": 2
        },
```

I know, that the frient A/S is in fact a device manufactured by Develco - but labeld as frient.
And I am pretty sure, that this is similar to the other frient device already available in the json - if you compare the model information.

Should I add the device as frient / frient A/S - or as Develco / Develco Products A/S ?
Or should I use the Manufacturer as it is shown in the Device Information of HA?
![image](https://github.com/andrew-codechimp/HA-Battery-Notes/assets/26391061/f5ed903d-256a-44af-aad5-c03e55fbf918)

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/andrew-codechimp/ha-battery-notes/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

---

### Reproduction steps

1.
2.
3.
...

### Debug logs

```text
---
```

**Comment by andrew-codechimp** [comment]
Hi, you would have to add the device to the library exactly as you have on your Device Info screen so frient A/S and HESZB-120

Different integrations like ZHA & Z2M surface the details differently, hence the duplication.
