### ISSUE TITLE
Support rechargeable batteries AAs & AAAs?

### ISSUE THREAD

**Issue by pskowronek** [andrew-codechimp/HA-Battery-Notes#1457]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/andrew-codechimp/ha-battery-notes/issues?q=is%3Aissue+label%3Aenhancement).

### Is your feature request related to a problem? Please describe.

When I put fully charged AAs or AAAs into a sensor, I see instantly or after a couple of hours that capacity drops to ~70% or so.

### Describe the solution you'd like

How to support rechargeable batteries AAs & AAAs?
Not sure yet, I know that it is a problem with sensors assuming 1.5V charge per cell, whereas rechargeable batteries have nominally ~1.2V (1.4-1.48V when freshly charged and they quickly drop to ~1.2 or so), but maybe if there was such an option to mark AA/AAA as rechargeable then Battery Notes could either recalculate their charge percentage, or at least not set the icon to yellow. 

### Describe alternatives you've considered

Just thinking at loud - if there was an option to state battery's capacity in mAh, then by observing percentage drop thru a day or week, estimate the power usage of the device in mA (should be more or less accurate for temp sensors and alike), this could be used to guestimate proper percentage and when the charge (and therefor voltage) will be too low to operate correctly (i.e. when voltage drop to a level where a sensor state 10 or 20% of battery).

### Additional context

It is not an easily task, probably quite a lot of research or consulting on HA or some other electronics forums would be required.

**Comment by andrew-codechimp** [comment]
This really depends on whether the integration provides a battery voltage/mAh sensor, very few do.
If you have that information available you can use the [battery low template](https://andrew-codechimp.github.io/HA-Battery-Notes/#battery-low-template) to set the boolean when the battery is low.  

You can set a very low threshold on those devices to only alert when they really are low, I do this a lot for hue devices that will run for months below 10%.

The colour on UI pages I can't really adjust as they are fixed at certain percentage values and I don't want to go faking percentages.
