### ISSUE TITLE
Unknown error after instalation

### ISSUE THREAD

**Issue by kubert96** [andrew-codechimp/HA-Battery-Notes#150]
## System Information

version | core-2023.12.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.6
os_name | Linux
os_version | 6.1.63-haos
arch | x86_64
timezone | Europe/Prague
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4830
Installed Version | 1.33.0
Stage | running
Available Repositories | 1428
Downloaded Repositories | 12

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | January 1, 2018 at 1:00 AM
relayer_connected | false
relayer_region | null
remote_enabled | false
remote_connected | false
alexa_enabled | true
google_enabled | true
remote_server | null
certificate_status | null
instance_id | b7f31363eaf74a8fb64d2d31642082e7
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 11.2
-- | --
update_channel | stable
supervisor_version | supervisor-2023.12.0
agent_version | 1.6.0
docker_version | 24.0.7
disk_total | 62.3 GB
disk_used | 30.5 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Samba share (12.2.0), File editor (5.7.0), Home Assistant Google Drive Backup (0.112.1), Zigbee2MQTT (1.34.0-1), MariaDB (2.6.1), ESPHome (2023.12.5), AppDaemon (0.16.0), Samba Backup (5.2.0), Advanced SSH & Web Terminal (17.0.0), Mosquitto broker (6.4.0), Zigbee2MQTT Edge (edge), MQTT Explorer (browser-1.0.3)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 6
views | 8
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | December 24, 2023 at 4:33 AM
-- | --
current_recorder_run | December 26, 2023 at 5:47 PM
estimated_db_size | 1073.08 MiB
database_engine | mysql
database_version | 10.6.12

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/andrew-codechimp/ha-battery-notes/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

After fresh install with HACS i cant add any deice. And no devices are discovered. 

![Screenshot 2023-12-26 at 17 45 24](https://github.com/andrew-codechimp/HA-Battery-Notes/assets/68554211/f9a59dbc-825d-4503-87fc-02b67310f48b)

### Reproduction steps

1. Install with HACS
2. Reboot Home Assistant (Whole HA)
3. Try add device with add integration

### Debug logs

```text
Dont have any log from integration
```

**Comment by andrew-codechimp** [comment]
Have you added battery_notes: to your configuration.yaml?
What version of battery notes do you have installed?

**Comment by kubert96** [comment]
Version 1.2.0 - Just Instaled. 

And what i ned to add to config i am missing this info...  Sorry if i am blind :D

**Comment by andrew-codechimp** [comment]
Ok, version 1.2 is stable.
In your home assistant configuration.yaml file add a new line at the bottom as follows, save the file and restart HA. 

battery_notes:

**Comment by kubert96** [comment]
OK a am blind :D .... Working as intended.

**Comment by andrew-codechimp** [comment]
Thanks for confirming. I'll try and handle this better in a future release now I know it is the issue.

**Comment by kubert96** [comment]
Ok and one more thing...

![Screenshot 2023-12-26 at 18 55 17](https://github.com/andrew-codechimp/HA-Battery-Notes/assets/68554211/da54b943-0901-453a-9369-a53c084512d5)

This is what i was expecting... 

![Screenshot 2023-12-26 at 18 56 18](https://github.com/andrew-codechimp/HA-Battery-Notes/assets/68554211/fa47524c-08bd-48e1-8403-29f897ca972f)
But i only see Battery type.. Not the management features :)

**Comment by kubert96** [comment]
![Screenshot 2023-12-26 at 18 57 23](https://github.com/andrew-codechimp/HA-Battery-Notes/assets/68554211/bf6553a3-3902-4df8-a8a6-30c64d5f3763)

**Comment by andrew-codechimp** [comment]
That's in beta and just released today, coming in a few days properly. 

If you wish to try this version please go into HACS, select Battery Notes and in the top right menu choose Redownload, switch on Show Beta Versions and select the latest version (starts with 1.3)

**Comment by kubert96** [comment]
Ooooo great :D Instaled and working :D Thank you for support. :)
