### ISSUE TITLE
Device: Tuya - Contact_Sensor_ikfjwqdbpnh154b9

### ISSUE THREAD

**Issue by igorsantos07** [andrew-codechimp/HA-Battery-Notes#1526]
### Manufacturer

Tuya

### Model

Contact Sensor (ikfjwqdbpnh154b9)

### Battery Type

AAA

### Battery Quantity

2

**Comment by igorsantos07** [comment]
@andrew-codechimp, I tried adding this device manually via the integration, but I was unable to select it from the dropdown. Should I file it as a bug?

I should note that this device is one of those odd ones with high/middle/low states, instead of numeric values. Should this add any special options to the battery DB?

**Comment by andrew-codechimp** [comment]
The drop down only lists devices that have a "proper" battery indicator so it won't show there.

You can add this to your configuration.yaml to show all devices but it will be a long list
```
battery_notes:
  show_all_devices: true
```

I've added it to the library, no need to do anything special though if you want the low notification you'll want a template as described [here](https://andrew-codechimp.github.io/HA-Battery-Notes/#battery-low-template).

**Comment by igorsantos07** [comment]
Cool, thanks man! It looks like I forgot how to use a sidebar menu on the docs :clown_face: Didn't notice the config section there, I recalled there was _something_ that would help on that problem, but wasn't sure which.

Thanks!
