### ISSUE TITLE
Google Nest Protect Smoke Alarm hard-wired model being autodetected

### ISSUE THREAD

**Issue by AnthonyBe** [andrew-codechimp/HA-Battery-Notes#153]
## System Information

version | core-2023.12.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.6
os_name | Linux
os_version | 6.1.63-haos
arch | x86_64
timezone | Australia/Sydney
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4989
Installed Version | 1.33.0
Stage | running
Available Repositories | 1367
Downloaded Repositories | 33

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | pending
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 11.2
-- | --
update_channel | stable
supervisor_version | supervisor-2023.12.0
agent_version | 1.6.0
docker_version | 24.0.7
disk_total | 30.8 GB
disk_used | 18.0 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Studio Code Server (5.14.2), Samba share (12.2.0), Check Home Assistant configuration (3.11.0), Advanced SSH & Web Terminal (17.0.0), ESPHome (2023.12.5)

</details>

<details><summary>Dashboards</summary>

dashboards | 14
-- | --
resources | 14
views | 13
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 21 December 2023 at 01:58
-- | --
current_recorder_run | 24 December 2023 at 23:04
estimated_db_size | 954.62 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

### Checklist

- [X] I have added `battery_notes:` to my configuration.yaml and restarted.
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/andrew-codechimp/ha-battery-notes/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Google Nest Protect Smoke Alarms are being auto-detected.
What it is not accounting for is that there are 2 models - hardwired (i.e. to household 120V/240V) and battery operated.

Mine are the hard-wired variety and so I have 2 discovered devices wanting to be configured.

Does this need some sort of tweak to the library.json to differentiate (if possible)?
Or just an option to exclude these devices from auto-detection?
Or do I just configure them as though they are battery operated, and then delete them?
Or do I configure them as "Irreplaceable"?

This is the relevant existing library entry:
```
        {
            "manufacturer": "Google",
            "model": "Topaz-2.7",
            "battery_type": "AA",
            "battery_quantity": 3
        },
```
Here's my wired model device:
![image](https://github.com/andrew-codechimp/HA-Battery-Notes/assets/17214552/f6027a3f-194f-4e3b-a02a-6b3f953cf3ea)

### Reproduction steps

1. Install integration and reboot
2.
3.
...

### Debug logs

```text
n/a
```

**Comment by andrew-codechimp** [comment]
Since Google don't differentiate models I'll remove this from the library and those with batteries can add it manually.

Thanks.
