### ISSUE TITLE
Allow negative battery levels as threshold

### ISSUE THREAD

**Issue by Aephir** [andrew-codechimp/HA-Battery-Notes#1535]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/andrew-codechimp/ha-battery-notes/issues?q=is%3Aissue+label%3Aenhancement).

### Is your feature request related to a problem? Please describe.

Some devices report negative values for battery level. They should not be changed when it reaches 0 %, but instead a negative value (-15% for the device in question)

### Describe the solution you'd like

Allow the threshold when setting up new device in Battery Notes

### Describe alternatives you've considered

None that use this integration.

### Additional context

Screenshot of device (Sure Petcare Hub). It is just about out of battery, but shows 0 % when it is "low" (i.e., wants you to change battery). But it can go down to - 16 % (as shown) and still work. So being able to set the threshold at e.g., - 15 %  would be great.
<img width="331" alt="Screenshot 2024-04-17 at 08 00 40" src="https://github.com/andrew-codechimp/HA-Battery-Notes/assets/20152788/8dcb318f-c6b2-40b9-982c-aad1f94833ac">

**Comment by andrew-codechimp** [comment]
To handle that you can add a [template](https://andrew-codechimp.github.io/HA-Battery-Notes/#battery-low-template) within the battery notes configuration for that device.

Something like `{{ states('sensor.mysensor_battery') | float(5) < 14 }}`
