### ISSUE TITLE
HACS no longer available, please update default installation method

### ISSUE THREAD

**Issue by evenprimes** [andrew-codechimp/HA-Battery-Notes#1536]
## System Information

version | core-2024.4.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.2
os_name | Linux
os_version | 6.6.25-haos
arch | x86_64
timezone | America/New_York
config_dir | /config

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 12.2
-- | --
update_channel | stable
supervisor_version | supervisor-2024.04.0
agent_version | 1.6.0
docker_version | 25.0.5
disk_total | 30.8 GB
disk_used | 2.6 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | 

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 0
views | 0
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | April 12, 2024 at 9:35 PM
-- | --
current_recorder_run | April 17, 2024 at 4:03 PM
estimated_db_size | 1.47 MiB
database_engine | sqlite
database_version | 3.44.2

</details>

None of this is relevant since I'm just doing to test setup in a VM before moving from a Docker installation.

### Checklist

- [X] I have added `battery_notes:` to my configuration.yaml and restarted.
- [X] I have read the [FAQ's](https://andrew-codechimp.github.io/HA-Battery-Notes/faq).
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/andrew-codechimp/ha-battery-notes/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

HACS has been shutdown due to legal threats:  https://www.reddit.com/r/homeassistant/comments/197xc0m/haier_is_shutting_down_the_hacs_integration_hon/

Please update the default installation instructions to the manual installation.

### Reproduction steps

1.
2.
3.
...
See above

### Debug logs

```text
n/a
```

### Diagnostics dump

n/a

**Comment by andrew-codechimp** [comment]
No, that's just Haier integration being removed from HACS.  HACS isn't shutting down.
