### ISSUE TITLE
New device - Kwikset Kevo smart lock

### ISSUE THREAD

**Issue by AnthonyBe** [andrew-codechimp/HA-Battery-Notes#155]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/andrew-codechimp/ha-battery-notes/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement).

### Is your feature request related to a problem? Please describe.

No

### Describe the solution you'd like

            "manufacturer": "Kwikset",
            "model": "Kevo",
            "battery_type": "AA",
            "battery_quantity": 4

### Describe alternatives you've considered

n/a

### Additional context

n/a

**Comment by andrew-codechimp** [comment]
Thanks, I've added it to the library
