### ISSUE TITLE
Deprecated alias Home Assistant 2024.5

### ISSUE THREAD

**Issue by tjorim** [andrew-codechimp/HA-Battery-Notes#1557]
## System Information

version | core-2024.5.0b0
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.2
os_name | Linux
os_version | 6.1.73-haos-raspi
arch | aarch64
timezone | Europe/Brussels
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4998
Installed Version | 1.34.0
Stage | running
Available Repositories | 1407
Downloaded Repositories | 77
HACS Data | pending

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | April 26, 2024 at 02:00
relayer_connected | true
relayer_region | eu-central-1
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | true
remote_server | eu-central-1-7.ui.nabu.casa
certificate_status | ready
instance_id | 98df8b6855fd40a682abea6ec3befbad
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 12.2
-- | --
update_channel | beta
supervisor_version | supervisor-2024.04.2
agent_version | 1.6.0
docker_version | 25.0.5
disk_total | 458.4 GB
disk_used | 25.6 GB
healthy | true
supported | true
board | yellow
supervisor_api | ok
version_api | ok
installed_addons | Spotify Connect (0.13.0), Advanced SSH & Web Terminal (17.2.0), File editor (5.8.0), Studio Code Server (5.15.0), Zigbee2MQTT (1.36.1-1), Home Assistant Google Drive Backup (0.112.1), The Lounge (0.19.1), Glances (0.21.1), Uptime Kuma (0.12.0), ESPHome (2024.4.1), Mosquitto broker (6.4.0), ankerctl (1.0.0-1), Firefox (1.1.0), Silicon Labs Flasher (0.2.3), AirCast (4.2.1), Music Assistant BETA (2.0.0b141), eBUSd (23.2.5)

</details>

<details><summary>Dashboards</summary>

dashboards | 4
-- | --
resources | 42
views | 15
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | April 14, 2024 at 15:29
-- | --
current_recorder_run | April 24, 2024 at 22:12
estimated_db_size | 662.33 MiB
database_engine | sqlite
database_version | 3.44.2

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Checklist

- [X] I have added `battery_notes:` to my configuration.yaml and restarted.
- [X] I have read the [FAQ's](https://andrew-codechimp.github.io/HA-Battery-Notes/faq).
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/andrew-codechimp/ha-battery-notes/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

```
Logger: homeassistant.helpers.typing
Source: helpers/deprecation.py:206
First occurred: 22:13:04 (3 occurrences)
Last logged: 22:15:47

EventType was used from battery_notes, this is a deprecated alias which will be removed in HA Core 2025.5. Use homeassistant.core.Event instead, please report it to the author of the 'battery_notes' custom integration
```

### Reproduction steps

1. Update Home Assistant to version 2024.5.0b0 and check the logs.

**Comment by andrew-codechimp** [comment]
Thanks for the heads up, this has been fixed in 2.2.7 just released.
