### ISSUE TITLE
Adaprox device TS0001_fingerbot_1 not discovered 

### ISSUE THREAD

**Issue by Lrnt-Prsn** [andrew-codechimp/HA-Battery-Notes#1562]
## System Information

version | core-2024.4.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.2
os_name | Linux
os_version | 6.1.73-haos-raspi
arch | aarch64
timezone | Europe/Paris
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4120
Installed Version | 1.34.0
Stage | running
Available Repositories | 1406
Downloaded Repositories | 79

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 15 mars 2025 à 01:00
relayer_connected | true
relayer_region | eu-central-1
remote_enabled | true
remote_connected | true
alexa_enabled | true
google_enabled | false
remote_server | eu-central-1-1.ui.nabu.casa
certificate_status | ready
instance_id | cd8929f5b799451594e67c5115cf8a2a
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 12.2
-- | --
update_channel | stable
supervisor_version | supervisor-2024.04.0
agent_version | 1.6.0
docker_version | 25.0.5
disk_total | 116.7 GB
disk_used | 22.8 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Samba share (12.3.1), File editor (5.8.0), Duck DNS (1.16.0), FTP (5.0.2), Mosquitto broker (6.4.0), Log Viewer (0.17.0), tydom2mqtt (3.4.3), Zigbee2MQTT (1.34.0-1), Home Assistant Google Drive Backup (0.112.1), Terminal & SSH (9.13.0), Advanced SSH & Web Terminal (17.2.0), MyElectricalData (0.12.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 6
-- | --
resources | 59
views | 27
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 24 mars 2024 à 03:30
-- | --
current_recorder_run | 25 avril 2024 à 11:12
estimated_db_size | 1993.14 MiB
database_engine | sqlite
database_version | 3.44.2

</details>

<details><summary>Sonoff</summary>

version | 3.7.2 (eb0a208)
-- | --
cloud_online | 0 / 4
local_online | 0 / 0

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Checklist

- [X] I have added `battery_notes:` to my configuration.yaml and restarted.
- [X] I have read the [FAQ's](https://andrew-codechimp.github.io/HA-Battery-Notes/faq).
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/andrew-codechimp/ha-battery-notes/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Adaprox TS0001_fingerbot_1 device is not discovered although it is present in the library like the other devices.
![Screenshot 2024-04-25 115332](https://github.com/andrew-codechimp/HA-Battery-Notes/assets/78692287/bc4173a1-b14f-4044-b5e5-916b51008a05)
![Screenshot 2024-04-25 115939](https://github.com/andrew-codechimp/HA-Battery-Notes/assets/78692287/7d8e626c-9165-4077-b65a-f17a76818790)

### Reproduction steps

1 - Reboot the HA instance
2 - Access to notification of new devices discovered
3 - Adaprox TS0001_fingerbot_1 does not appear in the list of new devices discovered

**Comment by andrew-codechimp** [comment]
Hi,
The model has to be exact, it looks like the library has a ZHA model whereas you are using Z2M.
I have just added the "Zigbee fingerbot plus (TS0001_fingerbot_1)" model and a restart of HA should pull the new library and allow it to be discovered.

**Comment by Lrnt-Prsn** [comment]
Hi,
Thank-you for your prompt response.
The device is now discovered.
I was at the origin of the first request to add this device and had incorrectly entered the name of the device.
Now I will know what title to indicate in my future requests!
