### ISSUE TITLE
Battery Notes icon is superseding that of the base integration for many of my devices

### ISSUE THREAD

**Issue by taw123** [andrew-codechimp/HA-Battery-Notes#1574]
### System Health details

First let me AGAIN compliment you on this much needed and appreciated integration. I was about to MANUALLY add attributes to each battery equipped device to centralize my tracking of battery types so this was truly a godsend....

Unfortunately I noticed in the past release (2024.4) and/or an update to BatteryNotes integration that many of my devices that HAVE associated BatteryNotes entities associated, now are badged with the BatteryNotes icon rather than that of the underlying Integration as they were previously. A pic might be worth a thousand words. 

<img width="1361" alt="Device list" src="https://github.com/andrew-codechimp/HA-Battery-Notes/assets/10588252/9470e281-d601-4686-8741-0f5d286a240d">

In this pic you will see SOME cases where BatteryNotes DOES subsume the badged icon and OTHER cases where the original integration icon was preserved.

- Bathroom is an Ecobee SmartSensor- with it's badge replaced by BatteryNotes
- Bedroom is ALSO an Ecobee SmartSensor- with original badge
- Espresso Machine is a YoLink moisture sensor- with original badge
- Foundation Sensor is a YoLink moisture sensor- with badge replaced by BatteryNotes

I have many others but I assume that should suffice to demonstrate the issue.

### It APPEARS that if BatteryNotes is listed FIRST in the device info, then IT'S icon will take precedence....
<img width="888" alt="Bathroom- Device detail" src="https://github.com/andrew-codechimp/HA-Battery-Notes/assets/10588252/81e1cacc-6787-4dbf-9f4d-c1fd8358e0b0">

### If not then the icon remains correct.
<img width="890" alt="Bedroom- Device detail" src="https://github.com/andrew-codechimp/HA-Battery-Notes/assets/10588252/dabde5ee-ded9-4174-85e1-5191fbfd81f9">

So......   How to EITHER revise the order in the device, and/or correct the badging so it always follows the base integration regardless of order?

### Checklist

- [X] I have added `battery_notes:` to my configuration.yaml and restarted.
- [X] I have read the [FAQ's](https://andrew-codechimp.github.io/HA-Battery-Notes/faq).
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/andrew-codechimp/ha-battery-notes/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Undesired Device icon replacement by battery home

### Reproduction steps

1.Nothing additional required 
2.
3.
...

### Debug logs

```text
BatteryNotes 2.2.7
HA Core 2024.4.4

I can give you full configs and logs but don't honestly believe that's at all relevant think it's simpler matter of how HA is building it's icon list and the variability of the associated integration icons. It really shouldn't be order dependent UNLESS you as in integration provider can CHOOSE the order when added, OR that order is established by when the device is FIRST integrated into HA as that WOULD have been the base integration as almost anyone (including me) would ever ADD a device...  Then we might add batteryynotes for said device.... Yah I'm an Engineer... ;)
```

**Comment by andrew-codechimp** [comment]
This is something I'd love to fix but have no control over the ordering of the devices.  It's a common issue with all integrations that supplement sensors to existing devices.

Here's a general discussion on it and also some back end architecture work going on, but the front end doesn't use it yet.
https://community.home-assistant.io/t/manage-primary-integration-for-devices/534948?u=codechimp
https://github.com/home-assistant/architecture/discussions/936
