### ISSUE TITLE
Support Hue Devices with ZHA

### ISSUE THREAD

**Issue by mightea** [andrew-codechimp/HA-Battery-Notes#160]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/andrew-codechimp/ha-battery-notes/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement).

### Is your feature request related to a problem? Please describe.

If Hue devices are integrated into HA using ZHA (e.g without the Hue Bridge) the model name is reported differently than with Hue. The current device database contains model names for Hue, e.g for a Wall Switch Module its `Hue wall switch module (RDM001)` but ZHA reports only `RDM001`.

### Describe the solution you'd like

It would be great if an alternative model name could be specified.

### Describe alternatives you've considered

Add separate entries for ZHA devices (e.g model name `RDM001`). I don't like this solution as it would add bloat and redundancy to the device library

### Additional context

Thanks for the great work anyway 👍

**Comment by andrew-codechimp** [comment]
I took the decision to go with separate entries for differing integrations a while ago for a few reasons.

It makes contributing to the library easier for those not experienced with json arrays.
I want to have an automatic submission form for library updates in the future, which are very limited via the GitHub issues template.
I don't expect the library to grow to a huge file size.

So if you want to add the ZHA or any other alternative feel free to submit a PR.

**Comment by mightea** [comment]
Okay makes sense. Thanks for the quick reply, I will prepare a PR then.
