### ISSUE TITLE
Feature: Battery value template

### ISSUE THREAD

**Issue by the01** [andrew-codechimp/HA-Battery-Notes#1620]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/andrew-codechimp/ha-battery-notes/issues?q=is%3Aissue+label%3Aenhancement).

### Is your feature request related to a problem? Please describe.

I had some issues where due to naming/renaming of devices, the entity id of the battery did not match what battery notes was expecting based on the device.
For most of the devices I was able to solve this by manually changing the battery entity id into what battery notes was looking for. However, this did not work for my shelly trvs.

### Describe the solution you'd like

I don't know how feasible this is, but it would help in these cases to also have a "Battery template", similar to how we have the "Battery low template" already. Instead of a boolean, it would return an int/float of the battery percentage.
This would allow using an entity as a source value that does not follow the expected naming scheme.
Additionally, this would allow the user to tweak their battery levels manually: correct devices that report a full charge as only 80%, translate voltage levels into battery %, combine two entities into a singular value, ...

### Describe alternatives you've considered

The "Battery low template" solves the basic need for low battery alerts.
However, this way I need to hard code the entity and the threshold into the template instead of using the global one and can't take advantage of other features, like the `battery_notes_battery_increased` event.

### Additional context

Thank you for your excellent work

**Comment by andrew-codechimp** [comment]
With the upcoming 3.2 release currently in beta you will be able to chose the correct entity for a device which will fix the main request.

The battery templating is the same as #1579, which I'm still thinking about options on.

**Comment by the01** [comment]
wow, that was fast! It's not yet working for me, but I have opened a bug report for that (#1622).
As far as the feature request is concerned, this should work.

Thank you for the quick solve!
