### ISSUE TITLE
Shelly Valve not getting battery+ entity

### ISSUE THREAD

**Issue by the01** [andrew-codechimp/HA-Battery-Notes#1622]
## System Information

version | core-2024.5.2
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.2
os_name | Linux
os_version | 6.6.29-haos
arch | x86_64
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4763
Installed Version | 1.34.0
Stage | running
Available Repositories | 1394
Downloaded Repositories | 25

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 12.3
-- | --
update_channel | stable
supervisor_version | supervisor-2024.05.1
agent_version | 1.6.0
docker_version | 25.0.5
disk_total | 46.5 GB
disk_used | 29.3 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Terminal & SSH (9.14.0), Studio Code Server (5.15.0), Mosquitto broker (6.4.0), Frigate (0.13.2), ESPHome (2024.4.2), Syncthing (1.19.0), Piper (1.5.0), Whisper (2.0.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 5
-- | --
resources | 11
views | 21
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | May 9, 2024 at 12:24
-- | --
current_recorder_run | May 10, 2024 at 11:07
estimated_db_size | 1613.82 MiB
database_engine | sqlite
database_version | 3.44.2

</details>

### Checklist

- [X] I have added `battery_notes:` to my configuration.yaml and restarted.
- [X] I have read the [FAQ's](https://andrew-codechimp.github.io/HA-Battery-Notes/faq).
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/andrew-codechimp/ha-battery-notes/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

This is a follow up to #1620.
I'm adding Battery Notes to a Shelly Valve (device name TRV-02), but I am only getting the
```
sensor.trv_02_battery_battery_last_replaced
button.trv_02_battery_battery_replaced
sensor.trv_02_battery_battery_type
```
entities, not *_battery_plus. As you can see, I already tried using v2.3.0 with the battery entity directly with no luck (adding the device has the same result, except that the entities are `sensor.trv_02_battery_type`, ..).
As described in the other ticket, I manged to solve this for other devices by renaming the battery entity. As far as I can tell it is already correct here or at least I'd expect the "add by entity id" route to work.
I have a second valve that shows the same behavior.

### Reproduction steps

1. Add device
2. Device/Entity (neither works)
3. Select shelly valve device (TRV-02) / Select shelly valve battery entity (sensor.trv_02_battery)
4. Next
5. Submit (No changes)
6. Success! -> Press finish

Not sure how easy this is reproduce as I only really had this issue with the valves.

### Debug logs

```text
2024-05-10 11:34:45.794 DEBUG (MainThread) [custom_components.battery_notes.library_updater] Getting library updates
2024-05-10 11:34:45.994 DEBUG (MainThread) [custom_components.battery_notes.library_updater] Updated library
2024-05-10 11:34:45.994 DEBUG (MainThread) [custom_components.battery_notes.config_flow] Looking up device Shelly Shelly Valve gen1 (SHTRV-01)
2024-05-10 11:34:45.994 DEBUG (MainThread) [custom_components.battery_notes.config_flow] Found device Shelly Shelly Valve gen1 (SHTRV-01)
2024-05-10 11:34:48.389 DEBUG (MainThread) [custom_components.battery_notes.coordinator] Manually updated battery_notes data
2024-05-10 11:34:48.389 DEBUG (MainThread) [custom_components.battery_notes.coordinator] Update coordinator
2024-05-10 11:34:48.389 DEBUG (MainThread) [custom_components.battery_notes.coordinator] Finished fetching battery_notes data in 0.000 seconds (success: True)
2024-05-10 11:34:48.394 DEBUG (MainThread) [custom_components.battery_notes.coordinator] Manually updated battery_notes data
2024-05-10 11:34:48.394 DEBUG (MainThread) [custom_components.battery_notes.coordinator] Update coordinator
2024-05-10 11:34:48.394 DEBUG (MainThread) [custom_components.battery_notes.coordinator] Finished fetching battery_notes data in 0.000 seconds (success: True)
```

### Diagnostics dump

```json
{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2024.5.2",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.12.2",
    "docker": true,
    "arch": "x86_64",
    "os_name": "Linux",
    "os_version": "6.6.29-haos",
    "supervisor": "2024.05.1",
    "host_os": "Home Assistant OS 12.3",
    "docker_version": "25.0.5",
    "chassis": "vm",
    "run_as_root": true
  },
  "custom_components": {
    "ui_lovelace_minimalist": {
      "documentation": "https://ui-lovelace-minimalist.github.io/UI/",
      "version": "v1.3.9",
      "requirements": [
        "aiofiles==0.8.0",
        "aiogithubapi>=22.2.4"
      ]
    },
    "composite": {
      "documentation": "https://github.com/pnbruckner/ha-composite-tracker/blob/3.4.1/README.md",
      "version": "3.4.1",
      "requirements": [
        "filetype==1.2.0"
      ]
    },
    "battery_notes": {
      "documentation": "https://andrew-codechimp.github.io/HA-Battery-Notes/",
      "version": "2.3.0",
      "requirements": []
    },
    "govee_lan": {
      "documentation": "https://github.com/wez/govee-lan-hass",
      "version": "1.0.0",
      "requirements": [
        "govee-led-wez>=0.0.15"
      ]
    },
    "browser_mod": {
      "documentation": "https://github.com/thomasloven/hass-browser_mod/blob/master/README.md",
      "version": "2.3.0",
      "requirements": []
    },
    "adaptive_lighting": {
      "documentation": "https://github.com/basnijholt/adaptive-lighting#readme",
      "version": "1.21.1",
      "requirements": [
        "ulid-transform"
      ]
    },
    "thermal_comfort": {
      "documentation": "https://github.com/dolezsa/thermal_comfort/blob/master/README.md",
      "version": "2.2.2",
      "requirements": []
    },
    "spook": {
      "documentation": "https://spook.boo",
      "version": "3.0.1",
      "requirements": []
    },
    "hacs": {
      "documentation": "https://hacs.xyz/docs/configuration/start",
      "version": "1.34.0",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
    "hass_agent": {
      "documentation": "https://github.com/LAB02-Research/HASS.Agent-Integration",
      "version": "2022.11.9",
      "requirements": []
    },
    "spook_inverse": {
      "documentation": "https://spook.boo",
      "version": "3.0.1",
      "requirements": []
    },
    "alarmo": {
      "documentation": "https://github.com/nielsfaber/alarmo",
      "version": "v1.10.1",
      "requirements": []
    },
    "frigate": {
      "documentation": "https://github.com/blakeblackshear/frigate",
      "version": "5.2.0",
      "requirements": [
        "pytz"
      ]
    }
  },
  "integration_manifest": {
    "domain": "shelly",
    "name": "Shelly",
    "codeowners": [
      "@balloob",
      "@bieniu",
      "@thecode",
      "@chemelli74",
      "@bdraco"
    ],
    "config_flow": true,
    "dependencies": [
      "bluetooth",
      "http",
      "network"
    ],
    "documentation": "https://www.home-assistant.io/integrations/shelly",
    "integration_type": "device",
    "iot_class": "local_push",
    "loggers": [
      "aioshelly"
    ],
    "quality_scale": "platinum",
    "requirements": [
      "aioshelly==9.0.0"
    ],
    "zeroconf": [
      {
        "type": "_http._tcp.local.",
        "name": "shelly*"
      }
    ],
    "is_built_in": true
  },
  "data": {
    "entry": {
      "entry_id": "c9d28145dc0774fd0b0df3a1aa2060f0",
      "version": 1,
      "minor_version": 1,
      "domain": "shelly",
      "title": "TRV-02",
      "data": {
        "host": "10.20.11.141",
        "sleep_period": 3600,
        "model": "SHTRV-01",
        "gen": 1
      },
      "options": {},
      "pref_disable_new_entities": false,
      "pref_disable_polling": false,
      "source": "zeroconf",
      "unique_id": "B4E3F9D61993",
      "disabled_by": null
    },
    "device_info": {
      "name": "TRV-02",
      "model": "SHTRV-01",
      "sw_version": "20240306-093529/v2.2.3@8f5e4729"
    },
    "device_settings": {
      "cloud": {
        "enabled": true
      },
      "coiot": {
        "enabled": true,
        "update_period": 3600,
        "peer": "10.20.3.4:5683"
      }
    },
    "device_status": {
      "wifi_sta": {
        "connected": true,
        "ssid": "**REDACTED**",
        "ip": "10.20.11.141",
        "rssi": -65
      },
      "time": "11:08",
      "has_update": false,
      "update": {
        "status": "unknown",
        "has_update": false,
        "new_version": "20240306-093529/v2.2.3@8f5e4729",
        "old_version": "20240306-093529/v2.2.3@8f5e4729",
        "beta_version": null
      },
      "ram_total": 97280,
      "ram_free": 22568,
      "fs_size": 65536,
      "fs_free": 59420,
      "uptime": 1152901
    },
    "bluetooth": "not initialized"
  }
}
```

**Comment by andrew-codechimp** [comment]
The battery_plus entity is only created if the entity you have selected has the following attributes

device_class: battery
unit_of_measurement: %

You can check the entity's attributes in the developer tools/states.
If it's a voltage or a normal/low indicator then battery plus will not work.

**Comment by the01** [comment]
That should be fine

State: 99
```yaml
state_class: measurement
unit_of_measurement: "%"
device_class: battery
friendly_name: TRV-02 battery
```

something else I could check?

**Comment by andrew-codechimp** [comment]
You're right that should be showing. 
I'll look into it.

**Comment by andrew-codechimp** [comment]
A question on that unit of measurement, did you get that info from the developer tools/states screen and does it have quotes round it there?
Looking at my test device there are no quotes and you can see its made a battery_plus entity for it.
A similar screenshot of your states may help track this down.

![CleanShot 2024-05-10 at 16 53 49@2x](https://github.com/andrew-codechimp/HA-Battery-Notes/assets/1849731/b9db10b5-0335-4f40-bd05-d7f6614ac789)

**Comment by the01** [comment]
I use the normal shelly integration in HA

<img width="768" alt="screen01" src="https://github.com/andrew-codechimp/HA-Battery-Notes/assets/4753009/21c679a5-94ef-47eb-ab8e-f3fef86f1caa">
<img width="318" alt="screen02" src="https://github.com/andrew-codechimp/HA-Battery-Notes/assets/4753009/ed7fc917-df92-4be9-bcff-55d76788d4af">

**Comment by andrew-codechimp** [comment]
I've not been able to replicate this but I've added some more debug logging in version 2.3.1 so if you can try that with logging enabled it might give some pointers.

**Comment by the01** [comment]
This is strange. No new output when I add it as a device, but as an entity I get:
`sensor.trv_02_battery is not a battery entity device_class: battery unit_of_measurement: None`
But as the screenshots show, HA thinks differently.

**Comment by andrew-codechimp** [comment]
That is odd, but shows why it can't create a battery, it has to match both device class and % units.
Stick with the entity method for this device, it will show better diags as it's looking directly at the specified entity.

If you are able to, can you look in the .storage/core.entity_registry and find the battery entity for this trv and post it's json, it should look something like this.

```
      {
        "aliases": [],
        "area_id": null,
        "capabilities": {
          "state_class": "measurement"
        },
        "config_entry_id": "95652777cffe095a0620be9ad467f22b",
        "device_class": null,
        "device_id": "05d31c2f6f9460ebf21335f67e14ba1f",
        "disabled_by": null,
        "entity_category": null,
        "entity_id": "sensor.esphm5matrix01_battery",
        "hidden_by": "integration",
        "icon": null,
        "id": "3582538deb33a5a0bf42af0133abf8a9",
        "has_entity_name": true,
        "name": null,
        "options": {
          "conversation": {
            "should_expose": false
          }
        },
        "original_device_class": "battery",
        "original_icon": null,
        "original_name": "Battery",
        "platform": "esphome",
        "supported_features": 0,
        "translation_key": null,
        "unique_id": "4C:75:25:96:F0:60-sensor-battery",
        "previous_unique_id": null,
        "unit_of_measurement": "%"
      },
```

**Comment by the01** [comment]
Yes, it is as you suspect, `"unit_of_measurement":null` on both my trvs.
I'll try removing the device and readding it.

Obviously your code is working as intended and the issue is elsewhere, but in case readding does not help, do you have any ideas what else I could check/try? (in case the response time for the shelly integration is not as fast as yours 😄 )

**Comment by the01** [comment]
Ok, never mind. Deleting add readding both TRVs worked perfectly. Not sure what went wrong priviously, but I even got a new entity (valve position) now.

And of course battery notes worked perfectly now.

So thank you very much for your fast, extensive and generous support!

**Comment by andrew-codechimp** [comment]
Glad you got it working, that was a strange one and at least it's got me to add some more diagnostic debugging if I need it in future.
