### ISSUE TITLE
Accept Date as input for set_battery_replaced service

### ISSUE THREAD

**Issue by darthsebulba04** [andrew-codechimp/HA-Battery-Notes#163]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/andrew-codechimp/ha-battery-notes/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement).

### Is your feature request related to a problem? Please describe.

Changed some batteries a few days ago, but unable to set the replacement date to anything but now().

### Describe the solution you'd like

If possible, change the service set_battery_replaced to take an optional date to set the replacement date of a battery.

### Describe alternatives you've considered

Maybe manually modifying the .storage info?

### Additional context

None really.

**Comment by andrew-codechimp** [comment]
I did look at this but since it's only going to be the first time you'll need to do this decided against it as it was getting complicated with UTC vs local time calculations for little long term use.
