### ISSUE TITLE
Missing eQ-3 devices

### ISSUE THREAD

**Issue by schacka** [andrew-codechimp/HA-Battery-Notes#166]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/andrew-codechimp/ha-battery-notes/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement).

### Is your feature request related to a problem? Please describe.

No

### Describe the solution you'd like

	{
		"manufacturer": "eQ-3",
		"model": "HM-CC-RT-DN",
		"battery_type": "AA",
		"battery_quantity": 2
	},
	{
		"manufacturer": "eQ-3",
		"model": "HM-Dis-EP-WM55",
		"battery_type": "AAA",
		"battery_quantity": 2
	},
	{
		"manufacturer": "eQ-3",
		"model": "HM-Sec-RHS",
		"battery_type": "LR44",
		"battery_quantity": 2
	},
	{
		"manufacturer": "eQ-3",
		"model": "HM-TC-IT-WM-W-EU",
		"battery_type": "AAA",
		"battery_quantity": 2
	},
	{
		"manufacturer": "eQ-3",
		"model": "HMIP-WRC2",
		"battery_type": "AAA",
		"battery_quantity": 2
	},
	{
		"manufacturer": "eQ-3",
		"model": "HmIP-DLD",
		"battery_type": "AA",
		"battery_quantity": 4
	},
	{
		"manufacturer": "eQ-3",
		"model": "HmIP-KRCK",
		"battery_type": "AAA",
		"battery_quantity": 1
	},
	{
		"manufacturer": "eQ-3",
		"model": "HmIP-STH",
		"battery_type": "AAA",
		"battery_quantity": 2
	},
	{
		"manufacturer": "eQ-3",
		"model": "HmIP-WRCD",
		"battery_type": "AAA",
		"battery_quantity": 2
	},
	{
		"manufacturer": "eQ-3",
		"model": "HmIP-eTRV-CL",
		"battery_type": "AA",
		"battery_quantity": 4
	}

### Describe alternatives you've considered

n/a

### Additional context

Merged and sorted:

	{
		"manufacturer": "eQ-3",
		"model": "HM-CC-RT-DN",
		"battery_type": "AA",
		"battery_quantity": 2
	},
	{
		"manufacturer": "eQ-3",
		"model": "HM-Dis-EP-WM55",
		"battery_type": "AAA",
		"battery_quantity": 2
	},
	{
		"manufacturer": "eQ-3",
		"model": "HM-ES-TX-WM",
		"battery_type": "AA",
		"battery_quantity": 4
	},
	{
		"manufacturer": "eQ-3",
		"model": "HM-Sec-RHS",
		"battery_type": "LR44",
		"battery_quantity": 2
	},
	{
		"manufacturer": "eQ-3",
		"model": "HM-TC-IT-WM-W-EU",
		"battery_type": "AAA",
		"battery_quantity": 2
	},
	{
		"manufacturer": "eQ-3",
		"model": "HMIP-SWDO",
		"battery_type": "AAA"
	},
	{
		"manufacturer": "eQ-3",
		"model": "HMIP-SWDO-I",
		"battery_type": "AAA",
		"battery_quantity": 2
	},
	{
		"manufacturer": "eQ-3",
		"model": "HMIP-SWDO-PL",
		"battery_type": "AAA",
		"battery_quantity": 2
	},
	{
		"manufacturer": "eQ-3",
		"model": "HMIP-WRC2",
		"battery_type": "AAA",
		"battery_quantity": 2
	},
	{
		"manufacturer": "eQ-3",
		"model": "HMIP-eTRV",
		"battery_type": "AA",
		"battery_quantity": 2
	},
	{
		"manufacturer": "eQ-3",
		"model": "HMIP-eTRV-2",
		"battery_type": "AA",
		"battery_quantity": 2
	},
	{
		"manufacturer": "eQ-3",
		"model": "HMIP-eTRV-B",
		"battery_type": "AA",
		"battery_quantity": 2
	},
	{
		"manufacturer": "eQ-3",
		"model": "HMIP-eTRV-C",
		"battery_type": "AA",
		"battery_quantity": 2
	},
	{
		"manufacturer": "eQ-3",
		"model": "HMIP-eTRV-E",
		"battery_type": "AA",
		"battery_quantity": 2
	},
	{
		"manufacturer": "eQ-3",
		"model": "HmIP-DLD",
		"battery_type": "AA",
		"battery_quantity": 4
	},
	{
		"manufacturer": "eQ-3",
		"model": "HmIP-KRCK",
		"battery_type": "AAA",
		"battery_quantity": 1
	},
	{
		"manufacturer": "eQ-3",
		"model": "HmIP-SCI",
		"battery_type": "AAA",
		"battery_quantity": 2
	},
	{
		"manufacturer": "eQ-3",
		"model": "HmIP-SLO",
		"battery_type": "AA",
		"battery_quantity": 2
	},
	{
		"manufacturer": "eQ-3",
		"model": "HmIP-SMI",
		"battery_type": "AA",
		"battery_quantity": 2
	},
	{
		"manufacturer": "eQ-3",
		"model": "HmIP-SMI55",
		"battery_type": "AAA",
		"battery_quantity": 2
	},
	{
		"manufacturer": "eQ-3",
		"model": "HmIP-SMO",
		"battery_type": "AA",
		"battery_quantity": 2
	},
	{
		"manufacturer": "eQ-3",
		"model": "HmIP-SRH",
		"battery_type": "AAA"
	},
	{
		"manufacturer": "eQ-3",
		"model": "HmIP-STH",
		"battery_type": "AAA",
		"battery_quantity": 2
	},
	{
		"manufacturer": "eQ-3",
		"model": "HmIP-SWDM",
		"battery_type": "AAA",
		"battery_quantity": 2
	},
	{
		"manufacturer": "eQ-3",
		"model": "HmIP-WRC6",
		"battery_type": "AAA",
		"battery_quantity": 2
	},
	{
		"manufacturer": "eQ-3",
		"model": "HmIP-WRCD",
		"battery_type": "AAA",
		"battery_quantity": 2
	},
	{
		"manufacturer": "eQ-3",
		"model": "HmIP-WTH-2",
		"battery_type": "AAA",
		"battery_quantity": 2
	},
	{
		"manufacturer": "eQ-3",
		"model": "HmIP-eTRV-CL",
		"battery_type": "AA",
		"battery_quantity": 4
	}

**Comment by andrew-codechimp** [comment]
Thanks, just added these
