### ISSUE TITLE
Add config option to hide battery replaced button/sensor

### ISSUE THREAD

**Issue by andrew-codechimp** [andrew-codechimp/HA-Battery-Notes#167]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/andrew-codechimp/ha-battery-notes/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement).

### Is your feature request related to a problem? Please describe.

Some people don't want this functionality and confuses when devices have had the button pressed x years ago

### Describe the solution you'd like

Add a config option to disable showing of battery replaced, enabled by default

### Describe alternatives you've considered

None

### Additional context

None

**Comment by uvjim** [comment]
Does this need to be an option? The entity description allows you as a developer to define the behaviour and the UI allows the user to either enable or disable an entity as required.

I guess all you need to do is decide whether they should be enabled by default or not and then users can decide after that on an entity by entity basis.

**Comment by andrew-codechimp** [comment]
After looking into it that's exactly what I'm doing now.  I've never really disabled entities much myself so didn't occur to me straight away.

**Comment by andrew-codechimp** [comment]
Released in version 1.3.4.  
See the FAQ for details
