### ISSUE TITLE
Battery+ sensor missing for some devices

### ISSUE THREAD

**Issue by chemelli74** [andrew-codechimp/HA-Battery-Notes#1672]
## System Information

version | core-2024.5.4
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
user | root
virtualenv | false
python_version | 3.12.2
os_name | Linux
os_version | 4.4.302+
arch | x86_64
timezone | Europe/Rome
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4996
Installed Version | 1.34.0
Stage | running
Available Repositories | 1395
Downloaded Repositories | 22

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 12
views | 14
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 11 maggio 2024 alle ore 18:43
-- | --
current_recorder_run | 19 maggio 2024 alle ore 16:55
estimated_db_size | 988.02 MiB
database_engine | sqlite
database_version | 3.44.2

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Checklist

- [X] I have added `battery_notes:` to my configuration.yaml and restarted.
- [X] I have read the [FAQ's](https://andrew-codechimp.github.io/HA-Battery-Notes/faq).
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/andrew-codechimp/ha-battery-notes/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

I noticed that some devices have the battery+ sensor, some others not.

### Reproduction steps

1. Install integration via HACS
2. Add battery_notes: to configuration.yaml
3. Restart HA
4. Check created sensors

**Comment by andrew-codechimp** [comment]
Hi, this depends on the device.  Only devices with a battery percentage will be picked up and a Battery+ created.
If your device has multiple entities that are batteries, like a voltage, low/normal or something else then try removing the device from battery notes and adding it back with the new Entity method, which will allow you to specify the battery entity directly, it can get confused with multiple battery entities.

**Comment by chemelli74** [comment]
Hi, doesn't looks like this is the case:

![image](https://github.com/andrew-codechimp/HA-Battery-Notes/assets/57354320/e1de838a-1558-478d-b76c-d31e82678843)

**Comment by andrew-codechimp** [comment]
OK, the Shelly integration had an issue a long time ago where the battery wasn't added properly.
Can you remove it from Battery Notes, remove it from the Shelly integration, then re add it.

See this issue for someone else with the same problem with a Shelly battery device.
https://github.com/andrew-codechimp/HA-Battery-Notes/issues/1622

**Comment by andrew-codechimp** [comment]
Yes, seems to be an issue with the early Shelly integration that didn't set the "unit_of_measurement": "%" correctly.
It's safe to modify entity_registry value and do a HA restart to get that properly recorded if you don't want the pain of re-pairing, I just don't like to suggest that for people unfamiliar with JSON, but by your use of jq there I'm guessing you're a hard core HA user!
