### ISSUE TITLE
Exclude Shelly H&T if powered by USB and not by battery

### ISSUE THREAD

**Issue by chemelli74** [andrew-codechimp/HA-Battery-Notes#1673]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/andrew-codechimp/ha-battery-notes/issues?q=is%3Aissue+label%3Aenhancement).

### Is your feature request related to a problem? Please describe.

SSIA

### Describe the solution you'd like

Exclude Shelly H&T if USB powered

### Describe alternatives you've considered

Manual excluding the device, but if in future you switch to battery you easily forget to re-enable it

### Additional context

-

**Comment by andrew-codechimp** [comment]
The way others have got around this multiple power source issue is to have the library with a MANUAL battery type, that way it won't get discovered and people can add it manually and put USB or battery type depending.
I'll update the library to this, I don't have one of these myself so didn't know it was dual power.
