### ISSUE TITLE
Shelly BLU Door/Window identification

### ISSUE THREAD

**Issue by chemelli74** [andrew-codechimp/HA-Battery-Notes#1676]
## System Information

version | core-2024.5.4
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
user | root
virtualenv | false
python_version | 3.12.2
os_name | Linux
os_version | 4.4.302+
arch | x86_64
timezone | Europe/Rome
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.34.0
Stage | running
Available Repositories | 1395
Downloaded Repositories | 22

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 12
views | 14
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 11 maggio 2024 alle ore 18:43
-- | --
current_recorder_run | 21 maggio 2024 alle ore 11:44
estimated_db_size | 988.02 MiB
database_engine | sqlite
database_version | 3.44.2

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Checklist

- [X] I have added `battery_notes:` to my configuration.yaml and restarted.
- [X] I have read the [FAQ's](https://andrew-codechimp.github.io/HA-Battery-Notes/faq).
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/andrew-codechimp/ha-battery-notes/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Didn't check the code for the identification, but seems that is based on a field that is not always present.

![image](https://github.com/andrew-codechimp/HA-Battery-Notes/assets/57354320/4fbe02bc-9cd2-47e9-aa11-361aa390dd0b)

### Reproduction steps

1. Install integration by HACS
2. Enable integration in configuration.yaml
3. Check battery+ for Shelly BLUE Door/Window device

**Comment by andrew-codechimp** [comment]
The discovery only checks on the Model & Make
In this case "BTHome sensor" by "Shelly"
I can't see that in the library so raise a new device request with the correct battery type please.

**Comment by chemelli74** [comment]
With Bluetooth is not so easy, unfortunately.
Often the vendor is not reported :-( as it all depends from the latest packet received that is influenced by the signal strength

**Comment by andrew-codechimp** [comment]
Oh, that sounds horrible.  I've not got any bluetooth myself, zigbee2mqtt everything.
That will have to be a manual add rather than a library discovery then.
