### ISSUE TITLE
Adding a device twice creates inconsistent state

### ISSUE THREAD

**Issue by zoechi** [andrew-codechimp/HA-Battery-Notes#1685]
## System Information

version | core-2024.5.2
-- | --
installation_type | Unknown
dev | false
hassio | false
docker | false
user | hass
virtualenv | false
python_version | 3.12.3
os_name | Linux
os_version | 6.6.21-hardened1
arch | x86_64
timezone | Europe/Vienna
config_dir | /var/lib/hass

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.34.0
Stage | running
Available Repositories | 1462
Downloaded Repositories | 61

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Dashboards</summary>

dashboards | 3
-- | --
resources | 30
views | 6
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | May 15, 2024 at 05:38
-- | --
current_recorder_run | May 23, 2024 at 21:52
estimated_db_size | 588.33 MiB
database_engine | sqlite
database_version | 3.45.2

</details>

### Checklist

- [X] I have added `battery_notes:` to my configuration.yaml and restarted.
- [X] I have read the [FAQ's](https://andrew-codechimp.github.io/HA-Battery-Notes/faq).
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/andrew-codechimp/ha-battery-notes/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

I have added my Nuki 2.0 Pro for the door sensor battery. It was not recognized automatically. I guess this is because it's using MQTT integration instead of Homekit.

I have 3 of them and added one twice accidentally.
Now it shows under 
Devices & Services > MQTT > Main Entrance > "Device Info"   
 "MQTT, Battery Notes, Battery Notes" 
but under 
Devices & Services > Battery Notes > Devices  
  is only one entry for this device.
When I delete the device from Battery Notes the entry is removed, one integration vanishes, but one remains    
Devices & Services > MQTT > Main Entrance > "Device Info"   
 "MQTT, Battery Notes" 

Main Entrance Battery notes still shows up in the Devices and Entities list (1 and 4 entries), but I can't delete it.

When I add the Mainentrance to Battery Notes again, it shows up there once as expected, but in Devices (2) and Entities (8) list, all the Battery Notes entries show up twice (2 and 8 entries).

### Reproduction steps

1. Add device to Battery Notes manually
2. Add the same device to Battery `Notes` manually again
3. Check the duplicate Battery Notes entries in Devices and Entities, while Battery Notes shows the device only once
4. Delete the device from Battery Notes
5. Check the orphan Battery Notes entries in Devices and Entities
6. Add the same device to Battery `Notes` manually again
7. Check the duplicate Battery Notes entries in Devices and Entities

**Comment by andrew-codechimp** [comment]
I have just tested this and I cannot add the same DEVICE twice. 
Are you sure you have not added entities?  If so they may be showing as the name of the entity rather than the name of the device within battery notes.
If you click on the Battery Notes within the Nuki device info panel that should take you to the correct battery notes entry where you can use the 3 dot menu to delete that battery notes.  The example below has the Battery which is an entity related battery note for the Ikea switch, even though I have a battery note for the device already.

![CleanShot 2024-05-25 at 12 22 01@2x](https://github.com/andrew-codechimp/HA-Battery-Notes/assets/1849731/a6d77d19-c916-42ba-88ca-46506f7907c5)

**Comment by zoechi** [comment]
Thank you a lot for looking into it. 
I'm currently fighting another problem that prevents me from checking. 
As soon as possible I'll try again and report back.
