### ISSUE TITLE
Discard devices which have already configured with battery notes in drop-down for adding new device

### ISSUE THREAD

**Issue by marcelhoogantink** [andrew-codechimp/HA-Battery-Notes#169]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/andrew-codechimp/ha-battery-notes/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement).

### Is your feature request related to a problem? Please describe.

Having many battery-powered devices and adding the last ones, the already configured devices are not relevant here and do 'hide' the not-configured ones.

### Describe the solution you'd like

See title

### Describe alternatives you've considered

NA

### Additional context

NA

**Comment by mikewren** [comment]
Great minds... I suggested this same enhancement to Andrew [over on Mastodon](https://mastodon.social/@mikewren/111653450369745375) yesterday and here's his response: "Unfortunately I don’t get to control that list, it’s built into HA and there’s limited scope for filtering."

**Comment by andrew-codechimp** [comment]
As Mike has said, unfortunately I can't fix this, agree it would be really nice to filter it down.  I think it would be hard for HA to provide hooks to that list easily to ever be able to implement this.

**Comment by marcelhoogantink** [comment]
Hi,

Maybe you can use this tiny template, witch gives the device_id's of all devices with 'battery_notes' to remove them from the list ?

`{{ integration_entities('battery_notes') | map('device_id') | unique | list}}`

This gives me the list of all devices witch are linked to battery_notes:

`
[
  "ba0d067b70cd50cd97bcd53ad14cfe5",
  "bf1a7cb3305809d2626cd412f84b50",
  "373b8ee56e45c00f6f91fe562d6c4a9",
  "6c444f5025b886b9255fec07fc827d4",
  "a726d5f47dbfc42f8110e1e6a010d05",
  "dd37cee8bf63f5e773569b83e0e3ad6",
  "0f7dae314b7f36c3a398e2160a4e5b3",
  "a20f40cad7cd3d836af48504e58f1c8",
  "2aacb8fcb277a5f0277026e7e94d759",
  "b5f3cf597f8026590a1464bae9d1d7d",
  "1cc94c52d3a35ba6f668f56792cbb99",
  "fde3da16c1bf97acf9a06333d001576",
  "fd6e33aaf4421fde895a0e2a69f85e4",
  "7a36cf72b53cb117ced091fd3849493"
]
`

I am not at the level of trying this on code level yet, so I propose this to you.

**Comment by andrew-codechimp** [comment]
Unfortunately the issue isn't identifying the devices with battery notes but excluding them from the list.

Home Assistant does not support a method to provide a list of device id's to exclude from the devices selector.

**Comment by danielbrunt57** [comment]
@andrew-codechimp Could you be so kind as to point me to the code where you present the devices selector list?
Thanks!

**Comment by andrew-codechimp** [comment]
It's here, just above is the definition for all devices if you have that config option set.
https://github.com/andrew-codechimp/HA-Battery-Notes/blob/7363117f22b54c44a45779650662c0f5327d82a4/custom_components/battery_notes/config_flow.py#L58

You'll see it being conditionally used here
https://github.com/andrew-codechimp/HA-Battery-Notes/blob/7363117f22b54c44a45779650662c0f5327d82a4/custom_components/battery_notes/config_flow.py#L161

I've looked into this twice and although entity selector allows exclusions, device selection doesn't, it's an annoying omission from Core.

**Comment by danielbrunt57** [comment]
Okay so this code:
```
        vol.Required(CONF_DEVICE_ID): selector.DeviceSelector(
            config=selector.DeviceSelectorConfig(
                entity=[
                    selector.EntityFilterSelectorConfig(
                        domain=Platform.SENSOR,
                        device_class=SensorDeviceClass.BATTERY,
                    ),
                    selector.EntityFilterSelectorConfig(
                        domain=Platform.BINARY_SENSOR,
                        device_class=SensorDeviceClass.BATTERY,
                    ),
                ]
            )
        ),
```
builds a list of `sensor `& `binary_sensor` entities whose `device_class` is `battery`, correct?
I'm by no means a python programmer but is there not a way to build that list as `list_all`, then build a list of `battery_notes` integration entities as `list_configured` and then use sets subtraction? like `new_list=list(set(list_all) - set(list_configured))` and use that new set in the `vol.Required(CONF_DEVICE_ID): selector.DeviceSelector()` function call?

> You can use sets:
> 
> main_list = list(set(list_2) - set(list_1))
> Output:
> 
> >>> list_1=["a", "b", "c", "d", "e"]
> >>> list_2=["a", "f", "c", "m"]
> >>> set(list_2) - set(list_1)
> set(['m', 'f'])
> >>> list(set(list_2) - set(list_1))
> ['m', 'f']
> Per @JonClements' comment, here is a tidier version:
> 
> >>> list_1=["a", "b", "c", "d", "e"]
> >>> list_2=["a", "f", "c", "m"]
> >>> list(set(list_2).difference(list_1))
> ['m', 'f']

So this...
```
config=selector.DeviceSelectorConfig(
                entity=[
                    selector.EntityFilterSelectorConfig(
                        domain=Platform.SENSOR,
                        device_class=SensorDeviceClass.BATTERY,
                    ),
                    selector.EntityFilterSelectorConfig(
                        domain=Platform.BINARY_SENSOR,
                        device_class=SensorDeviceClass.BATTERY,
                    ),
                ]
            )
``` 
might become something like this???
```
config=selector.DeviceSelectorConfig(
entity= 
  list( set( [
              selector.EntityFilterSelectorConfig(domain=Platform.SENSOR, device_class=SensorDeviceClass.BATTERY,),
              selector.EntityFilterSelectorConfig(domain=Platform.BINARY_SENSOR,device_class=SensorDeviceClass.BATTERY,),
             ] ) - set( [BATTERY_NOTES_CONFIGURED_ENTITIES_LIST] )
      )
)
```

**Comment by danielbrunt57** [comment]
I think it might be doable using the list(set_1 - set_2)!  But then again, I don't know python!

**Comment by andrew-codechimp** [comment]
I've had a look into this in more detail, your python suggestion was sound, it's the implementation of DeviceSelectorConfig thats the problem.
The entity parameter does not take a list of entities (it's naming is very confusing), but rather a list of EntityFilterSelectorConfig's, this is a small class which only allows filter definitions that are very limited in scope (integration, domain, device class and supported features), which is what I'm using to filter to only devices with batteries.

The options available to integrations mirrors what is available to blueprints [here](https://www.home-assistant.io/docs/blueprint/selectors/#device-selector), you'll see that further down the entity selector has specific parameters for included_entities and excluded_entities, this is what is missing from the device selector, that or included/excluded device id's which I could also make work, but device id's are not user friendly so understand why they are omitted.

I'll always keep an eye on whether these methods change in core, but for now there's no way to filter these.

**Comment by danielbrunt57** [comment]
Thank you for trying, again!  Based on your comment above, I looked at the code again with a different view of things and I can see now that it's like a closed black box into which you're passing which domain and device_class you want it to present.  That's pretty restictive for the programmer to select what should be displayed and, in this case, results in too broad of a selection list that the user should see.
```
DEVICE_SCHEMA = vol.Schema(
    {
        vol.Required(CONF_DEVICE_ID): selector.DeviceSelector(
            config=selector.DeviceSelectorConfig(
                entity=[
                    selector.EntityFilterSelectorConfig(
                        domain=Platform.SENSOR,
                        device_class=SensorDeviceClass.BATTERY,
                    ),
                    selector.EntityFilterSelectorConfig(
                        domain=Platform.BINARY_SENSOR,
                        device_class=SensorDeviceClass.BATTERY,
                    ),
                ]
            )
        ),
        vol.Optional(CONF_NAME): selector.TextSelector(
            selector.TextSelectorConfig(type=selector.TextSelectorType.TEXT),
        )
    }
)
```

I'm looking now though at the [Home Assistant Device Selectors](https://www.home-assistant.io/docs/blueprint/selectors/#device-selector) documentation and I can see the options are very limited.
What we need is either an `entity_exclude` variable , a `filter_out` variable, or just a single `exclude` variable with all possible conditions of `integration`, `domain`, `device_class`, `supported_features`, `manufacturer`, `model`.
