### ISSUE TITLE
Add ability to ignore discovered devices

### ISSUE THREAD

**Issue by mikedrews** [andrew-codechimp/HA-Battery-Notes#172]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/andrew-codechimp/ha-battery-notes/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement).

### Is your feature request related to a problem? Please describe.

I have multiple Aeotec Multisensors that have the capability to be powered by battery or 5vdc adapter.  All my Aeotec sensors are currently under 5vdc adapter power but they continue to be shown in discovered devices, understandably.  There is no option to ignore.

### Describe the solution you'd like

Please add an option to ignore devices.

### Describe alternatives you've considered

No alternative.

### Additional context

None

**Comment by andrew-codechimp** [comment]
Thanks for spotting the lack of ignore, I've not had a use for it myself but it should be an option.
3 lines of code was all it took so will be in the next release.

**Comment by mikedrews** [comment]
> Thanks for spotting the lack of ignore, I've not had a use for it myself but it should be an option. 3 lines of code was all it took so will be in the next release.

Excellent.  Thank you !

**Comment by andrew-codechimp** [comment]
Just got this into the release I was doing today, update to 1.3.4 and you get the ignore option.
