### ISSUE TITLE
New Language

### ISSUE THREAD

**Issue by darkobg79** [andrew-codechimp/HA-Battery-Notes#1742]
### Language

Serbian (latin)

**Comment by andrew-codechimp** [comment]
I have added the language into Crowdin and you can add translations [here](https://crowdin.com/project/battery-notes)

**Comment by darkobg79** [comment]
Translation is complete. ;)

**Comment by andrew-codechimp** [comment]
Thanks, this will be included in the next release.

**Comment by darkobg79** [comment]
Serbian has Cyrillic "sr"  and Latin "sr_Latn" variants. Please, Can you change translation file name to  sr_Latn.json? 
Thank you.

**Comment by darkobg79** [comment]
It must be sr-Latn.json

File name: sr-CS.json, dont snow translation
![image](https://github.com/andrew-codechimp/HA-Battery-Notes/assets/16548358/9ef079d6-9cc0-4513-971a-eb473b6da5b2)




.
.
.


File name: sr-Latn.json, it working
![image](https://github.com/andrew-codechimp/HA-Battery-Notes/assets/16548358/ad665507-9d0e-470b-9b3f-d7e123a6b660)

**Comment by andrew-codechimp** [comment]
I'm going to have to spend a bit of time looking at how to get that type of file out of crowdin, renaming it will just get overwritten.

**Comment by andrew-codechimp** [comment]
The bit of time was actually very little, the new release 2.3.9 now has a sr-Latn file pulling from crowdin.

**Comment by darkobg79** [comment]
Thank You :) Working now
