### ISSUE TITLE
Resolved: Insert Battery replacement date

### ISSUE THREAD

**Issue by Merril-r** [andrew-codechimp/HA-Battery-Notes#1757]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/andrew-codechimp/ha-battery-notes/issues?q=is%3Aissue+label%3Aenhancement).

### Is your feature request related to a problem? Please describe.

No

### Describe the solution you'd like

Would it be possible to add the ability to insert the battery replacement date when configuring a new entity for the first time. Currently you can select battery replaced but this may not be the date the battery was replaced. 

### Describe alternatives you've considered

Is there a place you can go and change the date replaced once you have updated the replacement date.

### Additional context

None

**Comment by andrew-codechimp** [comment]
Hi,

You can manually set a replacement date using the service call here
https://andrew-codechimp.github.io/HA-Battery-Notes/services/#battery_notesset_battery_replaced

**Comment by Merril-r** [comment]
Wow fast response. Got this to work. Thank you so much
