### ISSUE TITLE
New Device [Blink Camera]

### ISSUE THREAD

**Issue by c3p0vsr2d2** [andrew-codechimp/HA-Battery-Notes#178]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/andrew-codechimp/ha-battery-notes/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement).

### Is your feature request related to a problem? Please describe.

I was about to add an entry for Amazon Blink Cameras, but noticed that the model shows up as "unknown" in the device list, and is missing in the device page, in HomeAssistant. How can we add battery notes to such devices?

Will adding the following into library.json work?:

```
        {
            "manufacturer": "Blink",
            "battery_type": "AA",
            "battery_quantity": 2
        }
```

### Describe the solution you'd like

Any, as long as I can add battery notes to Blink XT2 cameras.

### Describe alternatives you've considered

na

### Additional context

na

**Comment by andrew-codechimp** [comment]
Battery Notes requires a model to be present so this won't work.
For this device I'd suggest just adding a note manually.
