### ISSUE TITLE
Download of update (2.3.9) fails - not found

### ISSUE THREAD

**Issue by zoechi** [andrew-codechimp/HA-Battery-Notes#1788]
## System Information

version | core-2024.6.3
-- | --
installation_type | Unknown
dev | false
hassio | false
docker | false
user | hass
virtualenv | false
python_version | 3.12.3
os_name | Linux
os_version | 6.6.32-hardened1
arch | x86_64
timezone | Europe/Vienna
config_dir | /var/lib/hass

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4946
Installed Version | 1.34.0
Stage | running
Available Repositories | 1456
Downloaded Repositories | 63

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | failed to load: timeout

</details>

<details><summary>Dashboards</summary>

dashboards | 3
-- | --
resources | 32
views | 8
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | June 12, 2024 at 05:53
-- | --
current_recorder_run | June 20, 2024 at 08:30
estimated_db_size | 644.01 MiB
database_engine | sqlite
database_version | 3.45.3

</details>

### Checklist

- [X] I have added `battery_notes:` to my configuration.yaml and restarted.
- [X] I have read the [FAQ's](https://andrew-codechimp.github.io/HA-Battery-Notes/faq).
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/andrew-codechimp/ha-battery-notes/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Update download hangs and logs show an error

### Reproduction steps

I just clicked update in HACS

I tried downloading manuall

This (from the error message) fails
$ curl https://github.com/andrew-codechimp/HA-Battery-Notes/releases/download/tags/2.3.9/battery_notes.zip
Not Found⏎

This succeeds                                                                                                              
$ curl https://github.com/andrew-codechimp/HA-Battery-Notes/releases/download/2.3.9/battery_notes.zip

Is there a tag missing or was `/tags` added by mistake?

### Debug logs

```text
Logger: custom_components.hacs
Source: custom_components/hacs/repositories/base.py:986
integration: HACS ([documentation](https://hacs.xyz/docs/configuration/start), [issues](https://github.com/hacs/integration/issues))
First occurred: 09:25:34 (10 occurrences)
Last logged: 09:29:25

<Integration andrew-codechimp/HA-Battery-Notes> Failed to download https://github.com/andrew-codechimp/HA-Battery-Notes/releases/download/tags/2.3.9/battery_notes.zip
```

**Comment by andrew-codechimp** [comment]
Hi, try again, this is probably a temporary issue with GitHub/internet connectivity.
The download URL is constructed by HACS so not something I can change and 7k people have the latest version so there's nothing wrong with it.

**Comment by zoechi** [comment]
Thank you. You were right. After a while it worked again.
