### ISSUE TITLE
FR: Remove "last_replaced" sensor for rechargeable battery devices

### ISSUE THREAD

**Issue by chemelli74** [andrew-codechimp/HA-Battery-Notes#1796]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/andrew-codechimp/ha-battery-notes/issues?q=is%3Aissue+label%3Aenhancement).

### Is your feature request related to a problem? Please describe.

I noticed that the sensor` last_replaced` is created for all devices.
Even for those that are known to have a rechargeable battery.

This leaves a sensor always in "unknown" state.
Would be nice to remove it for those devices.

### Describe the solution you'd like

Remove unneeded sensor.

### Describe alternatives you've considered

None

### Additional context

-

**Comment by andrew-codechimp** [comment]
Last Replaced would in this instance mean Last Recharged (whether it's plugged in or swapping a rechargeable pack) so this sensor will have value for many.
