### ISSUE TITLE
Automatically detect battery change

### ISSUE THREAD

**Issue by Mathea90** [andrew-codechimp/HA-Battery-Notes#1824]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/andrew-codechimp/ha-battery-notes/issues?q=is%3Aissue+label%3Aenhancement).

### Is your feature request related to a problem? Please describe.

Sometimes I forget to push the „battery replaced“ button when I change batteries of a device. I also find it to be a small annoyance to navigate to the device in Home Assistant to mark the battery as replaced when I remember to do it. As I would like to have this information documented in HA, I suggest an automatic battery replaced detection.

### Describe the solution you'd like

The time when the battery percentage or battery voltage of a device changes from a low value to close to maximum could be automatically saved in e.g. a „replaced battery detected“ entity. Maybe it would make sense to configure the threshold of when this logic should be triggered to make this detection robust against percentage fluctuations. 
In my opinion the best implementation would be if this detection would show up as a „repair“ notification in HA. If the user acknowledges the notification, the time value is automatically written into the „battery last replaced“ entity.

### Describe alternatives you've considered

The implementation could be realized in different ways:
1. Have a configurable battery replace detection threshold logic that is stored in the device database so that default values for devices are pre-configured. An automatic battery replaced detection triggers a repair notification which can be acknowledged or ignored by the user. An acknowledgement writes the time value into the battery last replaced entity.
2. use a global setting which turns the automatic battery replace detection on or off. If it‘s turned on, store the date without repair notification.
3. Have a second entity which stores the replaced date just as a reference so that the user can check back on it if he remembers that he forgot to manually press the button. He can put in the respective date automatically stored in the detection entity 
4. …

### Additional context

Thank you very much for this awesome integration. In my opinion further automating things and integrating intelligent functionality would be even more helpful.

**Comment by andrew-codechimp** [comment]
Hi, this functionality is already available. 

See an example automation using events

https://andrew-codechimp.github.io/HA-Battery-Notes/community/#battery-replaced

And a blueprint

https://andrew-codechimp.github.io/HA-Battery-Notes/community/#battery-replaced_1
