### ISSUE TITLE
New Device [Ecolink Garage Door]

### ISSUE THREAD

**Issue by c3p0vsr2d2** [andrew-codechimp/HA-Battery-Notes#183]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/andrew-codechimp/ha-battery-notes/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement).

### Is your feature request related to a problem? Please describe.

na

### Describe the solution you'd like

```
{
    "manufacturer": "Ecolink",
    "model": "TILTZWAVE1",
    "battery_type": "CR123A",
    "battery_quantity": 1
},
```

### Describe alternatives you've considered

na

### Additional context

na

**Comment by andrew-codechimp** [comment]
Thanks
