### ISSUE TITLE
No battery_plus and  battery_plus_low entity for shelly door/window2

### ISSUE THREAD

**Issue by digi303** [andrew-codechimp/HA-Battery-Notes#1843]
## System Information

version | core-2024.7.2
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 6.6.33-haos
arch | x86_64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.34.0
Stage | running
Available Repositories | 1468
Downloaded Repositories | 25
HACS Data | ok

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 12.4
-- | --
update_channel | beta
supervisor_version | supervisor-2024.06.2
agent_version | 1.6.0
docker_version | 26.1.4
disk_total | 468.7 GB
disk_used | 258.8 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | 
board | generic-x86-64
supervisor_api | ok
version_api | ok
installed_addons | Grafana (10.0.0), Samba share (12.3.1), Advanced SSH & Web Terminal (18.0.0), ESPHome (2024.6.6), Network UPS Tools (0.13.1), Frigate (Full Access) (0.13.2), Studio Code Server (5.15.0), SQLite Web (4.1.2), Mosquitto broker (6.4.1), Matter Server (6.2.1), InfluxDB (5.0.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 8
-- | --
resources | 7
error | /config/ui-lovelace.yaml not found
views | 66
mode | yaml

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 1. Juli 2024 um 14:02
-- | --
current_recorder_run | 13. Juli 2024 um 10:56
estimated_db_size | 2627.89 MiB
database_engine | sqlite
database_version | 3.45.3

</details>

### Checklist

- [X] I have added `battery_notes:` to my configuration.yaml and restarted.
- [X] I have read the [FAQ's](https://andrew-codechimp.github.io/HA-Battery-Notes/faq).
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/andrew-codechimp/ha-battery-notes/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

After adding Sheely Door/window 2 window sensors, there are no Battery_plus and battery_plus_low entities.
Even waking up these battery sensors beforehand does not bring about any change, nor does waking up and reloading the integration.
Sometimes the entities for battery sensors appear later, but this has not yet happened even after 3 days.
My other battery sensors (Aqara, etc.) all have the corresponding 5 entities...

Translated with DeepL.com (free version)

### Reproduction steps

1) Add Device
2) Open device
3) No Entitys
4) Delete Device, Restart etc. 
5) Everytime no change.

### Debug logs

```text
*/*
```

### Diagnostics dump

*/*

**Comment by andrew-codechimp** [comment]
This sounds similar to #1802 which is fixed in the latest beta.
I do not have these types of sensor myself so please let me know if this fixes it.

**Comment by digi303** [comment]
Unfortunately, version 2.3.11 does not change the behaviour.
Despite all the tricks (wake up, wait, reload etc.) I cannot create the corresponding entities.
Some pictures:
![Unbenannt](https://github.com/user-attachments/assets/4c622c15-0a6e-45a3-a6ff-6eb986c80cbb)
Shelly Window/door2
![Unbenannt](https://github.com/user-attachments/assets/a9a84bc2-f300-4348-a9b5-bf1afa5a3bf7)
Batterydevice also with Batterys (Aqara temperature)
![Unbenannt](https://github.com/user-attachments/assets/886cfbb9-6831-4eea-9cc0-1f55c813d500)

**Comment by andrew-codechimp** [comment]
Sorry, there is just something odd about the Shelly Door/Window sensor that's not getting it identified as a having a battery.
There's little I can do about this without having one to test myself so having to close this as unfixable.
