### ISSUE TITLE
Detected blocking call to open with args ('/config/custom_components/battery_notes/store.py', 'wb') inside the event loop 

### ISSUE THREAD

**Issue by derekoharrow** [andrew-codechimp/HA-Battery-Notes#1847]
## System Information

version | core-2024.7.2
-- | --
installation_type | Unsupported Third Party Container
dev | false
hassio | false
docker | true
user | homeassistant
virtualenv | true
python_version | 3.12.4
os_name | Linux
os_version | 5.15.0-113-generic
arch | x86_64
timezone | Europe/London
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4749
Installed Version | 1.34.0
Stage | running
Available Repositories | 1391
Downloaded Repositories | 40

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Dashboards</summary>

dashboards | 8
-- | --
resources | 21
views | 65
mode | storage

</details>

<details><summary>MercedesME 2020</summary>

api_endpoint_reachable | ok
-- | --
websocket_connection_state | connected
cars_connected | 1
version | v0.16.0

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 12 July 2024 at 18:17
-- | --
current_recorder_run | 16 July 2024 at 09:16
estimated_db_size | 7809.80 MiB
database_engine | mysql
database_version | 10.11.8

</details>

### Checklist

- [X] I have added `battery_notes:` to my configuration.yaml and restarted.
- [X] I have read the [FAQ's](https://andrew-codechimp.github.io/HA-Battery-Notes/faq).
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/andrew-codechimp/ha-battery-notes/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

HA 2024.7 reporting the following error on startup.

`2024-07-16 09:19:55.195 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to open with args ('/config/custom_components/battery_notes/store.py', 'wb') inside the event loop by custom integration 'hacs' at custom_components/hacs/repositories/base.py, line 600: zip_file.extractall(self.content.path.local) (offender: /usr/local/lib/python3.12/zipfile/__init__.py, line 1801: open(targetpath, "wb") as target:), please create a bug report at https://github.com/hacs/integration/issues`

This looks similar to other issues, but the line referenced is different from those other issues I believe.

### Reproduction steps

Just install battery notes and restart HA.

**Comment by andrew-codechimp** [comment]
This should be fixed a while ago and I'm not seeing it in my logs.
Can you ensure you have downloaded the most recent version of Battery Notes.

**Comment by derekoharrow** [comment]
It says I'm running 2.3.13 which is the latest pre-release?

**Comment by andrew-codechimp** [comment]
OK, that's the version I'm running and HA 2024.7.2 the same as you.
Interesting it actually logs the error as coming from HACS
`inside the event loop by custom integration 'hacs' at custom_components/hacs/repositories/base.py, line 600: `

I have seen an issue reported on HACS which will be fixed in the next version
https://github.com/hacs/integration/issues/3744

I am running HACS in Experimental mode which may be the reason I'm not getting the log warning.
