### ISSUE TITLE
entity object_id doesnt follow source entity for Ikea motion sensors

### ISSUE THREAD

**Issue by Mariusthvdb** [andrew-codechimp/HA-Battery-Notes#1858]
## System Information

version | core-2024.7.2
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 6.6.29-haos
arch | x86_64
timezone | Europe/Amsterdam
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.34.0
Stage | running
Available Repositories | 1398
Downloaded Repositories | 44
HACS Data | ok

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 31 augustus 2024 om 02:00
relayer_connected | true
relayer_region | eu-central-1
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | true
remote_server | eu-central-1-5.ui.nabu.casa
certificate_status | ready
instance_id | f51092f925
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 12.3
-- | --
update_channel | beta
supervisor_version | supervisor-2024.06.2
agent_version | 1.6.0
docker_version | 25.0.5
disk_total | 458.4 GB
disk_used | 25.8 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | 
board | generic-x86-64
supervisor_api | ok
version_api | ok
installed_addons | Log Viewer (0.17.0), Samba share (12.3.1), Terminal & SSH (9.14.0), Mosquitto broker (6.4.1), Z-Wave JS (0.6.2), ESPHome (2024.7.0), Studio Code Server (5.15.0), Home Assistant Google Drive Backup (0.112.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 10
-- | --
resources | 23
views | 117
mode | yaml

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 4 juli 2024 om 09:15
-- | --
current_recorder_run | 17 juli 2024 om 20:20
estimated_db_size | 2733.92 MiB
database_engine | sqlite
database_version | 3.45.3

</details>

### Checklist

- [X] I have added `battery_notes:` to my configuration.yaml and restarted.
- [X] I have read the [FAQ's](https://andrew-codechimp.github.io/HA-Battery-Notes/faq).
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/andrew-codechimp/ha-battery-notes/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

on all of my Ikea motion sensors, (which are integrated via the Homekit integration ) the Battery Notes entities dont use the '_motion' bit of the source entity object id's.

In itself, this is not really problematic, but, when templating and using 
```
    - entity_id: sensor.*_battery
      options:
        type: custom:template-entity-row
        state: >
          {{states(config.entity,with_unit=True)}}
        secondary: >
          Battery type: {{states(config.entity ~'_type')}}

```

this does become an issue

<img width="650" alt="Scherm­afbeelding 2024-07-18 om 10 53 33" src="https://github.com/user-attachments/assets/57095190-95a2-494e-b3c9-e292d7d79ea7">

main entity

<img width="566" alt="Scherm­afbeelding 2024-07-18 om 10 57 28" src="https://github.com/user-attachments/assets/26916450-5108-410b-83d9-d025e9206cc3">
<img width="600" alt="Scherm­afbeelding 2024-07-18 om 10 57 39" src="https://github.com/user-attachments/assets/2f67d238-b30b-4288-942a-9a21ce8b94c2">

battery notes entities:

<img width="611" alt="Scherm­afbeelding 2024-07-18 om 10 57 50" src="https://github.com/user-attachments/assets/ee5db46b-c18d-4e62-b0f8-adbe6ada5850">
<img width="594" alt="Scherm­afbeelding 2024-07-18 om 10 58 02" src="https://github.com/user-attachments/assets/16a5612e-f41e-46e6-b5dd-0c4cb2c67e6e">

given this is the only integration I currently experience the issue, and all others

<img width="1033" alt="Scherm­afbeelding 2024-07-18 om 10 59 27" src="https://github.com/user-attachments/assets/39438d01-b1bd-43c1-a7da-0f88e530b07f">

do well, I figured it to be an unexpected issue.

### Reproduction steps

1. just install and have all auto discovered
2.
3.
...

### Debug logs

will check when still required

### Diagnostics dump

[homekit_controller-e299b596c78deb0ecd4b6c766beae1bf-Garage sensor-384312c7470fb59081d09d8797aed950.json](https://github.com/user-attachments/files/16280505/homekit_controller-e299b596c78deb0ecd4b6c766beae1bf-Garage.sensor-384312c7470fb59081d09d8797aed950.json)

**Comment by andrew-codechimp** [comment]
Battery Notes creates the sensor names based on the current device name.  I'm guessing you renamed the device after it was added from Garage Motion Sensor to Garage Sensor but did not rename the entities, hence the mismatch between the real device entities and battery notes entities.

The easy fix is to edit the Battery Notes entities shown in pictures 4 & 5.
The harder fix, remove battery notes from the device, rename the device and choose to rename all entities, then add a battery note to the device again to get it to pick up the device name, the same as the real entities.

**Comment by Mariusthvdb** [comment]
Sorry but maybe you misread (I did edit the issue title accordingly):

I meant to indicate the object_id, not the name.

**Comment by andrew-codechimp** [comment]
Sorry, I don't understand this, there is no such thing as an object_id.
I think this will solve your issue with the dashboard entity list
The easy fix is to edit the Battery Notes entities shown in pictures 4 & 5.

**Comment by Mariusthvdb** [comment]
I will edit those, thanks for taking the time.

yet the fact this is only happening on the Ikea devices seems to indicate something programmatic and not my manual editing

given this is the convention for creating entities

`sensor.{{device_name}}_battery_plus`

I must find that out
