### ISSUE TITLE
Tuya plant sensor SGS01 - not showing notes

### ISSUE THREAD

**Issue by szupi-ipuzs** [andrew-codechimp/HA-Battery-Notes#1861]
## System Information

version | core-2024.7.3
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 5.15.0-113-generic
arch | x86_64
timezone | Europe/Warsaw
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.34.0
Stage | running
Available Repositories | 1471
Downloaded Repositories | 47
HACS Data | ok

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | January 9, 2025 at 01:00
relayer_connected | true
relayer_region | eu-central-1
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | false
remote_server | eu-central-1-1.ui.nabu.casa
certificate_status | ready
instance_id | *REDACTED*
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Dashboards</summary>

dashboards | 11
-- | --
resources | 31
views | 10
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | November 21, 2023 at 21:01
-- | --
current_recorder_run | July 20, 2024 at 10:14
estimated_db_size | 18691.11 MiB
database_engine | sqlite
database_version | 3.45.3

</details>

<details><summary>Sonoff</summary>

version | 3.7.3 (e240aaf)
-- | --
cloud_online | 0 / 0
local_online | 0 / 0

</details>

### Checklist

- [X] I have added `battery_notes:` to my configuration.yaml and restarted.
- [X] I have read the [FAQ's](https://andrew-codechimp.github.io/HA-Battery-Notes/faq).
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/andrew-codechimp/ha-battery-notes/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

I can see that this sensor was added via #1643, but it's not showing up in my setup. I use it via Tuya BLE integration and it reports the manufacturer as Tuya and not TuYa - maybe that's the issue... Should I submit a PR to add a separate device entry with the other manufacturer name?

![obraz](https://github.com/user-attachments/assets/86046a36-aa92-4b5f-b853-c87a43d91d51)

### Reproduction steps

1. 
2.
3.
...

**Comment by andrew-codechimp** [comment]
Hi, it's not the Tuya name as I don't compare case. 
The model is slightly different with a plant sensor prefix so probably a different integration. 
Use the new device issue to request adding it exactly as your screenshot and I'll add it.

**Comment by szupi-ipuzs** [comment]
I have 3 such devices and I think the integrations sets the "model" field so how they are seen in tuya app. For example here's the screenshot for the other device (note the 02 suffix):
![obraz](https://github.com/user-attachments/assets/f1e26428-d1aa-4f8a-a7c9-24cb510da9bd)

Will this still work if I add the PR with the "model" set to SGS01 without the suffix? Do you do partial matching?

**Comment by andrew-codechimp** [comment]
The TuyaBLE integration seems to not do Model names correctly, they shouldn't change just because you have 2 of them.
The library won't be able to pick up these extra ones so just add them manually.
