### ISSUE TITLE
[Help/Enhancement] Adding battery notes for entities

### ISSUE THREAD

**Issue by c3p0vsr2d2** [andrew-codechimp/HA-Battery-Notes#188]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/andrew-codechimp/ha-battery-notes/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement).

### Is your feature request related to a problem? Please describe.

Arlo integration in HA does not create new devices - instead there are entities created for each camera (temperature/battery/camera/etc entities). How can one add battery notes to entities, instead of devices?

### Describe the solution you'd like

na

### Describe alternatives you've considered

na

### Additional context

na

**Comment by andrew-codechimp** [comment]
Sorry that's not going to be possible to handle, sounds a very odd integration to do that rather than devices.
