### ISSUE TITLE
Adjust Zooz ZSE42 battery types

### ISSUE THREAD

**Issue by rohankapoorcom** [andrew-codechimp/HA-Battery-Notes#1910]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/andrew-codechimp/ha-battery-notes/issues?q=is%3Aissue+label%3Aenhancement).

### Is your feature request related to a problem? Please describe.

Zooz has multiple versions of the ZSE42. Older models use the CR2032 battery. Newer models use the CR2450 battery. This seems to be getting changed regularly in the device listing as people with different models fill out new device requests.

Most recently this was changed in https://github.com/andrew-codechimp/HA-Battery-Notes/issues/1496

### Describe the solution you'd like

I'd like there to be a way to either differentiate between the two devices (and store both in the device listing) or to prevent updates to this device from being populated automatically into the device listing. In the current architecture, this device needs to be kept at "MANUAL"

Related discussions have happened in #1266, https://github.com/andrew-codechimp/HA-Battery-Notes/pull/1228#issuecomment-1978201980

### Describe alternatives you've considered

Alternatively, users can maintain their own device listing, but that seems like a bad idea.

### Additional context

N/A

**Comment by andrew-codechimp** [comment]
This device was recently discussed [here](https://github.com/andrew-codechimp/HA-Battery-Notes/discussions/1899#discussioncomment-10170734) 
At the moment if the make, model and hardware version are identical I cannot have the library differentiate.
I have set it to MANUAL and will keep it like that until perhaps the integration owner is able to make a differentiation with the new Model ID coming in 2024.8 of Home Assistant.
Battery Notes can only work with the data presented, raise this with the integration owner and see if you can get them to use the new Model ID, or at least have a suffix to the existing model.

**Comment by rohankapoorcom** [comment]
Thanks for the link to the discussion section (the one place I didn't check).

Does setting it to manual prevent it from being updated automatically by a new device request issue?

The reason I opened this issue is that it used to work in manual mode for me for the past couple of months and then recently I got a new ZSE42 and it was suggesting an incorrect battery again. Maybe my library version was out of date since I see the current main branch has it set correctly.

**Comment by andrew-codechimp** [comment]
It was changed back to Manual only a few days ago, you should get the library updated daily unless there was a problem the last time it tried to update.
I try to pay attention to device updates to sanity check them but occasionally they slip through, I may have to think about auto discarding changes to manual devices if this happens often.

**Comment by rohankapoorcom** [comment]
>  I may have to think about auto discarding changes to manual devices if this happens often.
That was my suggestion with this feature request.

Thanks for the explanation!

**Comment by rohankapoorcom** [comment]
Hey @andrew-codechimp - this happened again in https://github.com/andrew-codechimp/HA-Battery-Notes/pull/4026

Would you be able to revert again please?

**Comment by andrew-codechimp** [comment]
Thanks for the heads up.  I've just reverted it.

I'll add discarding manual devices to my todo list now.

**Comment by rohankapoorcom** [comment]
Thanks for the quick response!
