### ISSUE TITLE
battery notes but for climate entities 

### ISSUE THREAD

**Issue by warrentc3** [andrew-codechimp/HA-Battery-Notes#1971]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/andrew-codechimp/ha-battery-notes/issues?q=is%3Aissue+label%3Aenhancement).

### Is your feature request related to a problem? Please describe.

no

### Describe the solution you'd like

I would love to have something similar to battery notes for climate entity types related to changing the air filters (sizes/count), routine maintenance, etc. 

### Describe alternatives you've considered

ics 

### Additional context

plausible? reasonable?

**Comment by andrew-codechimp** [comment]
This would be something separate from Battery Notes, I have thought a Maintenance Notes could be nice but that would be a different project and have a far wider scope of details captured. I have no plans to start a new integration but perhaps suggest in the HA Forums and see if someone else would be interested in developing it, they could take a lot of Battery Notes for that.
