### ISSUE TITLE
Battery % "unknown" for device NAS-AB02B2

### ISSUE THREAD

**Issue by urgali** [andrew-codechimp/HA-Battery-Notes#1984]
## System Information

version | core-2024.8.1
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 6.10.5-x64v3-xanmod1
arch | x86_64
timezone | Europe/Rome
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4993
Installed Version | 1.34.0
Stage | running
Available Repositories | 1390
Downloaded Repositories | 9
HACS Data | ok

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 2
views | 6
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | August 7, 2024 at 3:29 PM
-- | --
current_recorder_run | August 16, 2024 at 5:06 PM
estimated_db_size | 664.49 MiB
database_engine | sqlite
database_version | 3.45.3

</details>

### Checklist

- [X] I have added `battery_notes:` to my configuration.yaml and restarted.
- [X] I have read the [FAQ's](https://andrew-codechimp.github.io/HA-Battery-Notes/faq).
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/andrew-codechimp/ha-battery-notes/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Battert percentage for device:
Alarm (NAS-AB02B2) by Neo

is reported as "unknown" although device is in library (https://github.com/andrew-codechimp/HA-Battery-Notes/pull/1008).

every other value is correctly reported:
![image](https://github.com/user-attachments/assets/27bf3503-f400-4241-b160-badf3ff9340e)

### Reproduction steps

1. Open Battery Notes GUI in Homeassistant
2. Manually add device via "ADD DEVICE"
3. Select "Device (recommended)" as association type
4. Select device from drop down menu
5. Battery type alredy is right one (CR123A Lithium)
6. Set battery quantity (2)
7. Set battery low treshold (10)
8. Leave Battery low template blank
9. Click submit

### Diagnostics dump

[home-assistant_battery_notes_2024-08-16T15-28-07.956Z.log](https://github.com/user-attachments/files/16638725/home-assistant_battery_notes_2024-08-16T15-28-07.956Z.log)

**Comment by andrew-codechimp** [comment]
The battery is your devices battery, not battery notes so there's nothing I can do there. 
If it's zigbee they sometimes take a while to show.
