### ISSUE TITLE
Recharged last..

### ISSUE THREAD

**Issue by itnassol** [andrew-codechimp/HA-Battery-Notes#201]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/andrew-codechimp/ha-battery-notes/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement).

### Is your feature request related to a problem? Please describe.

Is it possible to have a recharged last on those rechargeable sensors like the Shelly.

### Describe the solution you'd like

Like the replaced but recharged

### Describe alternatives you've considered

None

### Additional context

None

**Comment by andrew-codechimp** [comment]
I think since recharged/replaced will be mutually exclusive the replaced indicator will work for this requirement rather than duplicating it.
