### ISSUE TITLE
excluding an Unknown devices

### ISSUE THREAD

**Issue by keidischoi** [andrew-codechimp/HA-Battery-Notes#2043]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/andrew-codechimp/ha-battery-notes/issues?q=is%3Aissue+label%3Aenhancement).

### Is your feature request related to a problem? Please describe.

I think it would be nice to exclude equipment that is marked as "Unknown". It's inconvenient because even if you disable it, it will show up again after an update.

### Describe the solution you'd like

-
![스크린샷 2024-09-04 222617](https://github.com/user-attachments/assets/bb59923e-3838-45e1-9280-598804d78043)

### Describe alternatives you've considered

-

### Additional context

-

**Comment by andrew-codechimp** [comment]
This is a UI issue rather than an integration one, all integrations will show unknown/unavailable when a sensor value cannot be retrieved. 
If you are using Auto Entities or Battery State Card you could add an exclusion filter to remove those from your dashboard.
