### ISSUE TITLE
Remove battery+ sensors

### ISSUE THREAD

**Issue by DevSecNinja** [andrew-codechimp/HA-Battery-Notes#2115]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/andrew-codechimp/ha-battery-notes/issues?q=is%3Aissue+label%3Aenhancement).

### Is your feature request related to a problem? Please describe.

Is it possible to remove the battery+ sensors? I don't know what their function are, but I have an automation that gets all the battery stats and outputs only the batteries <20% and this causes two entities to be returned. The regular battery entity and the battery+ entity. Thank you!

### Describe the solution you'd like

Battery+ entities removed

### Describe alternatives you've considered

N/A

### Additional context

N/A

**Comment by andrew-codechimp** [comment]
The Battery+ sensor is designed to be a replacement for the original battery with additional attributes (battery type etc) helping to create better dashboards/notifications with them.  I won't be removing them from this integration.

Have you tried hiding the original battery in config and then excluding hidden sensors as per the config and template sample below, or you could filter those ending with Battery+

```
battery_notes:
  hide_battery: true
```

```
{{ states.sensor
  | selectattr('attributes.device_class', 'defined')
  | selectattr('attributes.device_class', 'eq', 'battery')
  | rejectattr('entity_id', 'is_hidden_entity')
  | map(attribute='attributes.friendly_name' )
  | list }}
```

**Comment by DevSecNinja** [comment]
Thank you @andrew-codechimp!
