### ISSUE TITLE
Entity friendly names not translated

### ISSUE THREAD

**Issue by terba** [andrew-codechimp/HA-Battery-Notes#2187]
### System Health details

.

### Checklist

- [X] I have added `battery_notes:` to my configuration.yaml and restarted.
- [X] I have read the [FAQ's](https://andrew-codechimp.github.io/HA-Battery-Notes/faq).
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/andrew-codechimp/ha-battery-notes/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

The generated entities doesn't get their names from the translation files. For example the friendly name of "My best sensor Battery+" should be "My best sensor Elem+" with the Hungarian translation. Maybe a space is missing before the Battery+ and Elem+ strings here:
![kép](https://github.com/user-attachments/assets/24c1b704-d094-4c07-9ed9-81fe56b35b78)

### Reproduction steps

1.
2.
3.
...

**Comment by andrew-codechimp** [comment]
Hi, the lack of a space is intentional as in certain circumstances there's no device name prefix. 
Is this only happening with battery+ or other entities?
Can you clear your browser cache, I've sometimes seen issues with translation strings being cached.

**Comment by terba** [comment]
Hi, this is happening with all the entities created by the integration. The attribute names are ok.
Cleared the cache, even recreated an association, but the strings are untranslated.
![kép](https://github.com/user-attachments/assets/ff3ddb35-3770-4370-a4dc-98703cf4bd0b)

**Comment by andrew-codechimp** [comment]
Thanks for checking the cache and providing those details, I'll have a look into it.

**Comment by andrew-codechimp** [comment]
Using the Sun integration as a test I changed my user and system language from English to Hungarian and the friendly names were still English.
I then deleted the Battery Note for the Sun, re-added whilst I was set to Hungarian and it added them correctly translated as can be seen below.
Can you have a look if this fixes it for you?  I know there is some confusion about what translation is used if your user and system language are different, maybe you had one set to English when creating the battery notes for your device?

Apologies I am only an English speaker so localisation is tricky for me to test.

![CleanShot 2024-10-04 at 11 07 20](https://github.com/user-attachments/assets/c4a44980-63b6-4b8d-b0b2-956bd998885a)

![CleanShot 2024-10-04 at 11 14 19](https://github.com/user-attachments/assets/84da3f77-8cb5-451c-9880-4689160b0a92)

**Comment by terba** [comment]
That was it, thanks! The system language was not set (defaulted to English), and the user profile language was not used for the entity names but all the others. I set the system language in configuration.yaml to Hungarian, and it works.

**Comment by andrew-codechimp** [comment]
Thanks for confirming. 
I did some reading up and this is a common issue with home assistant and not just battery notes, not a great user experience.
