### ISSUE TITLE
Add support for devices that don't report battery levels in percentages

### ISSUE THREAD

**Issue by almirus** [andrew-codechimp/HA-Battery-Notes#2202]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/andrew-codechimp/ha-battery-notes/issues?q=is%3Aissue+label%3Aenhancement).

### Is your feature request related to a problem? Please describe.

Currently, you can't add devices that don't provide a percentage-based battery level, like a [smoke detector](https://www.zigbee2mqtt.io/devices/TS0601_smoke_6.html). It only reports battery status as: low, medium, or high.

### Describe the solution you'd like

I want support for devices without percentage-based battery levels to be added. It could be possible to emulate the battery level with dummy percentages: low = 10%, medium = 50%, high = 100%.

### Describe alternatives you've considered

-

### Additional context

![image](https://github.com/user-attachments/assets/c27e2c8d-6283-4693-909d-836be3dc8821)

**Comment by zoechi** [comment]
I was just trying to accomplish something like that. I added an entity (door sensor of my Nuki smart lock) with a "battery low template", but it doesn't show up in states (Developer tools).

I have configured the battery state card with

```yaml
filter:
  include:
    - name: entity_id
      value: '*_battery_plus'
```
To get the new battery shown I can add
```yaml
    - name: entity_id
      value: '*_battery_critical'
```
But it gets shown with state `On` which isn't too helpful and a question mark as icon and also there is no secondary info about the the battery type shown like with the other batteries.

I thought I might be lacking some knownledge, but then I found this issue. So, it looks like I'm not the only one struggling with this.

**Comment by andrew-codechimp** [comment]
You can't add a battery state like this as a battery plus, but you can add a template for the boolean battery low to reflect a low battery and trigger events.  I'm not sure if I'll ever add this into battery plus as there are a lot of permutations for these unusual devices.
https://andrew-codechimp.github.io/HA-Battery-Notes/#battery-low-template

**Comment by zoechi** [comment]
I had the template a bit wrong but fixing it didn't change anything. 

Also using `'*_battery_plus_low'` for the filter doesn't help.

So there is no way to get the battery type shown as secondary info for such batteries?

**Comment by andrew-codechimp** [comment]
Unfortunately not, the template only affects the binary sensor, not the battery plus one, so it's no use in dashboards the way you are wanting to use it.
If I can ever think of a nice way of handling this I will, but it's got to be flexible and easy to configure/understand for me to add it.

**Comment by zoechi** [comment]
I understand. 
Thanks a lot anyway for this cool integration :rocket:

**Comment by andrew-codechimp** [comment]
Thanks for your suggestion but there are also batteries with voltages, ones with Normal or Low and also ones that just display a binary low natively, that we'd also want to have as a sudo percentage.
I'm not forgetting about this, but as stated there are a lot of things to consider and also make it easy to use.

**Comment by andrew-codechimp** [comment]
So I've been experimenting with ideas around this and it turns out without any code changes you can create a Template Helper and have Battery Notes pick it up and create a Battery+ sensor.

I've documented how to do this here, feedback appreciated if you have issues.

https://andrew-codechimp.github.io/HA-Battery-Notes/entities/#adding-a-battery-percentage

**Comment by almirus** [comment]
@andrew-codechimp success! thank you!
![image](https://github.com/user-attachments/assets/3c312502-9480-445a-a195-737dd6fb770f)
