### ISSUE TITLE
Wrong Version Number

### ISSUE THREAD

**Issue by Pyromane** [andrew-codechimp/HA-Battery-Notes#2240]
## System Information

version | core-2024.10.3
-- | --
installation_type | Home Assistant Core
dev | false
hassio | false
docker | false
user | root
virtualenv | true
python_version | 3.12.3
os_name | Linux
os_version | 6.8.12-2-pve
arch | x86_64
timezone | Europe/Vienna
config_dir | /root/.homeassistant

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Dashboards</summary>

dashboards | 7
-- | --
resources | 0
views | 1
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 9. Oktober 2024 um 22:37
-- | --
current_recorder_run | 18. Oktober 2024 um 18:59
estimated_db_size | 28.59 MiB
database_engine | sqlite
database_version | 3.45.1

</details>

### Checklist

- [X] I have added `battery_notes:` to my configuration.yaml and restarted.
- [X] I have read the [FAQ's](https://andrew-codechimp.github.io/HA-Battery-Notes/faq).
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/andrew-codechimp/ha-battery-notes/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

The version number displayed in the integeration does not match the one from github, see screenshot.

I suspect this is because the version number in manifest.json has not been incremented for a long time: custom_components/battery_notes/manifest.json

Non-HACS users cannot recognize whether they are using the current version or not.
![version](https://github.com/user-attachments/assets/3dd9cc57-caba-460d-afa2-cc33b04b866a)

### Reproduction steps

1.-
2.
3.
...

**Comment by andrew-codechimp** [comment]
Please use the zip file within the release when manually updating, there is a process to update the manifest in the zip with the correct version when a release is created.
This will ensure a stable version.
