### ISSUE TITLE
Forcing device detections

### ISSUE THREAD

**Issue by soupman98** [andrew-codechimp/HA-Battery-Notes#2262]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/andrew-codechimp/ha-battery-notes/issues?q=is%3Aissue+label%3Aenhancement).

### Is your feature request related to a problem? Please describe.

How do I force battery/device detection. I have a long established environment with 200+ devices, but B+ doesn't seem to detect any of them. I have battery_notes: in my configuration.yaml with detection set to on. 

### Describe the solution you'd like

B+ provides a way to "detect now"

### Describe alternatives you've considered

manually adding a LOT of devices - yuck

### Additional context

love the integration just doesn't seem to find as many (any) devices as expected.

**Comment by andrew-codechimp** [comment]
Hi,
Device detection happens at HA Restart, it also happens approx every 24 hours after a restart, the library is also updated at this point.
I don't want to introduce a manual re-detect to avoid excessive download of the library from GitHub (someone will set it to re-discover every minute I'm sure!)

**Comment by soupman98** [comment]
@andrew-codechimp  just realized.. does it matter if the devices are actually coming over to HA from Smart Things integration?

**Comment by andrew-codechimp** [comment]
Smart things devices will be supported, it just depends on whether people have added them to the library.
Different integrations present the manufacturer/model differently, for example Ikea devices are duplicated which is probably ZHA and Zigbee2MQTT.  If your devices are in [this doc](https://github.com/andrew-codechimp/HA-Battery-Notes/blob/main/library.md) but with slightly different info then it won't match.
You can add it to the library to help others and also allow discovery where you have multiples as long as you wait until the library is updated.

**Comment by soupman98** [comment]
Therein lies the rub, my HA device inventory shows <unknown> for Manufacturer and Model in HA, but shows some other details in S/T (attached)
![image](https://github.com/user-attachments/assets/abef0c6b-a06a-4cf0-8866-885ff44c849c)

I think I added the 1117-S a while back. I have 8 of these in S/T that didn't get picked up in B+.  
I may eventually move my S/T devices to HA, but for now, they pass thru.

**Comment by andrew-codechimp** [comment]
Looking at that second screenshot from HA all your devices have unknown in the manufacturer and model fields, which means the Smart Things integration is not passing through these when it creates the HA device.
These data elements are what makes Battery Notes device detection work, without them being populated it can't determine the device.
Not sure if that's Smart Things in general or the integration but I'm afraid you'll never get device detection working with those.

**Comment by soupman98** [comment]
Thanks @andrew-codechimp. That was my fear. Not sure why ST / HA wouldn't do the pass thru, but even if it did, it looks like some of the Edge drivers that you have to add to ST for devices now, provide an odd value "SmartThingsCommunity". This stuff is all so fun <not>

![image](https://github.com/user-attachments/assets/1fa909f3-2f03-4df8-b9c3-1fe183918043)

**Comment by andrew-codechimp** [comment]
Thanks, well I hope you find it useful for your non Smart Things devices.
I've never tried ST but this sort of experience will ensure I steer clear of it.
