### ISSUE TITLE
Device: _TZE200_myd45weu - Quirk: zhaquirks.tuya.ts0601_sensor.TuyaSoilSensor

### ISSUE THREAD

**Issue by defuuss** [andrew-codechimp/HA-Battery-Notes#2271]
### Manufacturer

_TZE200_myd45weu 

### Model

Quirk: zhaquirks.tuya.ts0601_sensor.TuyaSoilSensor

### Battery Type

AA

### Battery Quantity

2

**Comment by defuuss** [comment]
![image](https://github.com/user-attachments/assets/ba56afe2-6fd3-41bb-aab4-e208eb61c371)

**Comment by andrew-codechimp** [comment]
That didn't need a model of Quirk, I'll fix it.
