### ISSUE TITLE
New Language - Chinese Traditional & Simplified

### ISSUE THREAD

**Issue by rhuba8324** [andrew-codechimp/HA-Battery-Notes#2414]
### Language

`zh-Hant` for Chinese Traditional
and
`zh-Hans` for Chinese Simplified

**Comment by andrew-codechimp** [comment]
Hi,

Crowdin is suggesting zh-TW for Traditional and zh-CN for Simplified.

Can you clarify why the Hant/Hans suffixes should be used here?  Is this what HA is using elsewhere?

**Comment by rhuba8324** [comment]
HA, and the majority of custom integration uses Hant/Hans to my knowledge.
I guess it's made so to be more inclusive? Since CN and TW are not the only places using Hans and Hant. Not pretty sure about that though.

**Comment by andrew-codechimp** [comment]
Thanks for the explanation, only speaking English I'm no expert in these things.
I've added the new languages to Crowdin with the appropriate mapping codes, please add your translations and I'll merge them in the next release.
https://crowdin.com/project/battery-notes
