### ISSUE TITLE
Any hope for restart-less updates?

### ISSUE THREAD

**Issue by pskowronek** [andrew-codechimp/HA-Battery-Notes#2458]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/andrew-codechimp/ha-battery-notes/issues?q=is%3Aissue+label%3Aenhancement).

### Is your feature request related to a problem? Please describe.

I'm always frustrated that restart of HA is required after updates of Battery Notes. So far, I restart HA only because of this plugin, no other updates demands that (at least it is not something it caught my eye).

### Describe the solution you'd like

Avoid restarting somehow? 

### Describe alternatives you've considered

I dunno

### Additional context

Nevertheless, awesome HACS plugin :)

**Comment by andrew-codechimp** [comment]
Unfortunately all custom integrations require a restart of HA when updated, it's just dashboard UI related components that don't so I'm afraid there's nothing I can do there, it's just the way HA works internally.

I do try to limit releases to at most once a week (except those that have turned on beta's) and at the moment I am going through quite a tidy up so they are almost every week but that will slow soon.
