### ISSUE TITLE
Device: SAF Tehnika - null

### ISSUE THREAD

**Issue by derobert** [andrew-codechimp/HA-Battery-Notes#2462]
### Manufacturer

SAF Tehnika

### Model

null

### Model ID

null

### HW Version

null

### Battery Type

AA

### Battery Quantity

2

**Comment by derobert** [comment]
From the JSON:

```json
    "device": {
      "manufacturer": "SAF Tehnika",
      "model": null,
      "model_id": null,
      "hw_version": null
    }
```

I'm not sure how to tell an Aranet 4 apart from other Aranet devices.

**Comment by derobert** [comment]
@andrew-codechimp 
The GUI just omits the fields; 
![Screenshot_20241209-234531](https://github.com/user-attachments/assets/34235c19-bb3f-4d02-9fdf-fd4f44b8632f)

And editing the battery notes shows blanks:
![Screenshot_20241209-234742](https://github.com/user-attachments/assets/68a83b66-a577-42d8-ab83-2208adb3ad68)

Those nulls are what you get from downloading the diagnostics JSON.

**Comment by andrew-codechimp** [comment]
Thanks for the clarification, the null within diagnostics indicates that the Aranet integration does not expose a model.
The library needs a model to match against, so in this case you will have to add them manually as you have done so.
There are not many integrations that skip the model but I've seen a few unfortunately.
