### ISSUE TITLE
After updating the latest version 2.7.2 on HAOS 14.0 setup.py failed

### ISSUE THREAD

**Issue by Blcktape** [andrew-codechimp/HA-Battery-Notes#2469]
## System Information

version | core-2024.11.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 6.6.63-haos
arch | x86_64
timezone | Europe/Amsterdam
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 4987
Installed Version | 2.0.1
Stage | running
Available Repositories | 1473
Downloaded Repositories | 8

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 14.0
-- | --
update_channel | stable
supervisor_version | supervisor-2024.11.4
agent_version | 1.6.0
docker_version | 27.2.0
disk_total | 30.8 GB
disk_used | 8.9 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | kvm
board | ova
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.8.0), Home Assistant Google Drive Backup (0.112.1), Mosquitto broker (6.4.1), Zigbee2MQTT (1.42.0-2), Advanced SSH & Web Terminal (19.0.0), ZigStar TI CC2652P/P7 FW Flasher (0.4.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 1
views | 2
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | November 26, 2024 at 13:03
-- | --
current_recorder_run | December 4, 2024 at 12:51
estimated_db_size | 209.57 MiB
database_engine | sqlite
database_version | 3.45.3

</details>

### Checklist

- [X] I have added `battery_notes:` to my configuration.yaml and restarted.
- [X] I have read the [FAQ's](https://andrew-codechimp.github.io/HA-Battery-Notes/faq).
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/andrew-codechimp/ha-battery-notes/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

After updating the latest version 2.7.2 on HAOS 14.0

`2024-12-04 12:51:11.005 ERROR (MainThread) [homeassistant.setup] Error during setup of component battery_notes
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 416, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/battery_notes/__init__.py", line 140, in async_setup
    await discovery_manager.start_discovery()
  File "/config/custom_components/battery_notes/discovery.py", line 90, in start_discovery
    library = await Library.factory(self.hass)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/battery_notes/library.py", line 116, in factory
    await library.load_libraries()
  File "/config/custom_components/battery_notes/library.py", line 91, in load_libraries
    default_json_data = await self.hass.async_add_executor_job(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/battery_notes/library.py", line 49, in _load_library_json
    return cast(dict[str, Any], json.load(file))
                                ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

### Reproduction steps

1. Updated to HAOS 14.0
2. Update to "HA-Battery-Notes" 2.7.2

**Comment by Blcktape** [comment]
It required a second reboot to come back online.

**Comment by andrew-codechimp** [comment]
Thanks for the quick report, I'll check this out and work on a fix.

**Comment by andrew-codechimp** [comment]
Fixed in version 2.7.3 just released.

Silly mistake on my part, thanks for the feedback.
