### ISSUE TITLE
New Language: Portuguese from Portugal (PT) or (pt-PT)

### ISSUE THREAD

**Issue by FragMenthor** [andrew-codechimp/HA-Battery-Notes#2470]
### Language

Portuguese from Portugal (PT) or (pt-PT)

**Comment by FragMenthor** [comment]
Already requested in Crowdin. Thanks

**Comment by andrew-codechimp** [comment]
Thanks, Portuguese (PT) is now available to add translations in Crowdin
https://crowdin.com/project/battery-notes

**Comment by FragMenthor** [comment]
Done. Thank you!
