### ISSUE TITLE
Bluetooth device integration within the BTHOME integration

### ISSUE THREAD

**Issue by vitjurasek** [andrew-codechimp/HA-Battery-Notes#2481]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/andrew-codechimp/ha-battery-notes/issues?q=is%3Aissue+label%3Aenhancement).

### Is your feature request related to a problem? Please describe.

The integration does not include bluetooth connected devices at all, which are integrated within the core BTHOME integration
https://www.home-assistant.io/integrations/bthome

### Describe the solution you'd like

I have a number of Shelly devices (for example Shelly BLU devices - door and window magnets) that I have working in HA, but the Battery Notes add-on can't find them.

![image](https://github.com/user-attachments/assets/e252c0c3-ffd7-489a-97b9-3214ad356357)

The devices have a published battery status. 

![image](https://github.com/user-attachments/assets/e5d316de-92a4-479b-8719-50ab9aef5c86)

![image](https://github.com/user-attachments/assets/62345ed4-03eb-471b-99ae-7a7f11e0f385)

![image](https://github.com/user-attachments/assets/bd1afc5e-d2d1-4563-a023-e1559f036211)

My most common device is Shelly BLU Door & Window (SHELLY-BLU-DW-W)
1× 3V CR2032

![image](https://github.com/user-attachments/assets/b32bc18f-695b-40ae-86cb-ba2588c03834)

### Describe alternatives you've considered

Can such integrated devices be included in automatic detection? How to proceed? Is there any work-around yet?

### Additional context

Can such integrated devices be included in automatic detection? How to proceed? Is there any work-around yet?

**Comment by vitjurasek** [comment]
FYI: It is interesting that, for example, this device (and two others) was found automatically and offered by the integration for addition. The other 17 pieces (exactly the same) were not.

![image](https://github.com/user-attachments/assets/f705cba2-941d-47b2-8039-7970518db5a2)

Author of BTHome integration (core of HA):
BTHome sensor is a default name shown if the model is not a known model, as you wrote besides the name everything will work the same. I have started working on some infra to allow easier adding of model names, I hope to finish it soon. I will link to this issue when it is ready.

Me: And is there any way to user-complement this hardware to make it known for integration?
You can just rename the device, there is nothing else other than the name

**Comment by andrew-codechimp** [comment]
That's very odd, I just don't see how it would pick those devices up as they aren't in the library.
Hopefully BTHome will get more specific with it's device identifiers, it would be good to have these detected.

The manufacturer, model and model id are all set by the integration at the time of discovery, whilst these are in the core.device_registry json file I think most integrations set/overwrite these at startup so I don't think there's a permanent way to change/complement this yourself.
