### ISSUE TITLE
IKEA E1812 listed with wrong battery type

### ISSUE THREAD

**Issue by hmmbob** [andrew-codechimp/HA-Battery-Notes#2509]
### System Health details

not relevant

### Checklist

- [X] I have added `battery_notes:` to my configuration.yaml and restarted.
- [X] I have read the [FAQ's](https://andrew-codechimp.github.io/HA-Battery-Notes/faq).
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/andrew-codechimp/ha-battery-notes/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

My IKEA E1812 Tradfri SHortcut button was correctly recognized, but with the wrong battery type in the database. It's currently listed to use CR2450, but it uses CR2032. See photo.
It was previously listed correctly, but was changed through https://github.com/andrew-codechimp/HA-Battery-Notes/pull/1626 

![image](https://github.com/user-attachments/assets/06380464-3159-4a37-9d4f-9df049dbfe69)

### Reproduction steps

n/a

**Comment by andrew-codechimp** [comment]
Thanks for the correction, I've updated this.
