### ISSUE TITLE
battery_age entity

### ISSUE THREAD

**Issue by gerrieg** [andrew-codechimp/HA-Battery-Notes#2519]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/andrew-codechimp/ha-battery-notes/issues?q=is%3Aissue+label%3Aenhancement).

### Is your feature request related to a problem? Please describe.

no problem

### Describe the solution you'd like

The age of the battery in days would be interesting for me, perhaps it would be worth implementing.

### Describe alternatives you've considered

I need to add an entity for each device with the calculation myself

### Additional context

no additional context

**Comment by andrew-codechimp** [comment]
As the battery replaced is a standard datetime you can obviously calculate this and I don't see any other devices offering a separate numeric entity of days when they have a datetime, but get where you are coming from as you'll have to create a template helper for each device.
What's your use case for this?  Maybe there's a better way to handle this.

**Comment by andrew-codechimp** [comment]
I'm still not sure why you need days whilst battery last replaced will show you a friendly formatted days/months ago.
You can use auto entities card to then show a list of all your batteries to quickly glance down, sorted by last replaced.

Battery life according to manufacturer would be very variable, how often is the sensor triggered, brand of battery etc.
