### ISSUE TITLE
Device: switchbot - Leak Detector

### ISSUE THREAD

**Issue by luc-ass** [andrew-codechimp/HA-Battery-Notes#2524]
### Manufacturer

switchbot

### Model

Leak Detector

### Battery Type

AAA

### Battery Quantity

2

**Comment by luc-ass** [comment]
This device will be added to one of the next versions of Home Assistant. Here is a screenshot from my dev-instance:
![Bildschirmfoto 2024-12-22 um 21 07 48](https://github.com/user-attachments/assets/38c9339d-7251-4693-bf88-ad7aae536d9e)

**Comment by andrew-codechimp** [comment]
Thanks, I'll add it ready for the device to appear.
