### ISSUE TITLE
Allow the original Device icon to be retained when adding a battery note

### ISSUE THREAD

**Issue by lucasstinis** [andrew-codechimp/HA-Battery-Notes#26]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/andrew-codechimp/ha-battery-notes/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

When a battery note is added for a device, the device's icon changes to the HA Battery Notes icon automatically. There's currently option to change this behaviour.

### Describe the solution you'd like

Having a global(?) setting related to the integration that allows the user to choose to retain the original device icon.

### Describe alternatives you've considered

Accepting this can't be changed :-)

### Additional context

![image](https://github.com/andrew-codechimp/HA-Battery-Notes/assets/11487668/50a3d803-994c-4917-9609-f122e38be773)

Top entry shows the HA Battery Notes icon, bottom entry shows the original device's icon.

**Comment by andrew-codechimp** [comment]
Unfortunately Home Assistant does not have a concept of "original" device and picks an icon at random.
This also happens with the Change Device Type of Switch helper and other integrations like PowerCalc and UniFi.

It niggles me as well, but this would require a change to HA rather than the integrations.

**Comment by lucasstinis** [comment]
Fair enough! I'll drop it as a suggestion on the official HA Github, but doubt this will get any priority. Thanks for getting back to me and, more importantly, thanks for creating this little gem of an integration.

**Comment by stevegroom** [comment]
> Unfortunately Home Assistant does not have a concept of "original" device and picks an icon at random. This also happens with the Change Device Type of Switch helper and other integrations like PowerCalc and UniFi.
> 
Perhaps worth noting - I have SONOS and Unifi integrations - all SONOS devices are network devices. Every SONOS speaker has the correct icon, Unifi icon did not get used for the SONOS devices.

**Comment by andrew-codechimp** [comment]
I have UniFi myself and it's hit and miss what icon a device gets. 
There's a discussion about it [here](https://community.home-assistant.io/t/manage-primary-integration-for-devices/534948)

**Comment by andrew-codechimp** [comment]
I did see that and have played with it but it's still not consistent.
