### ISSUE TITLE
Battery Library

### ISSUE THREAD

**Issue by dankarization** [andrew-codechimp/HA-Battery-Notes#27]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/andrew-codechimp/ha-battery-notes/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

This is an interesting project, but for now it requires to manually fill every sensor you have with battery type. 

### Describe the solution you'd like

It would be much more useful if it had a base like [powercalc](**[url](https://github.com/bramstroker/homeassistant-powercalc/blob/master/docs/supported_models.md)**) where different users can add a note, then it will search for the same entities in your configuration, and autopopulate them.

### Describe alternatives you've considered

Didn't see any integrations like yours tbh

### Additional context

I am willing to populate this database with 30-50 sensor types or even more, just so it would be filled at the start

**Comment by dankarization** [comment]
Glad to hear it. Will be waiting for an upgrade :3

**Comment by magicus** [comment]
Dang it! This was the second idea I came here to suggest, and it too was already suggested. :) 

I wonder if it would be possible to kickstart a library by extracting information e.g. from ZB2M database at https://www.zigbee2mqtt.io/supported-devices. I know at least some devices have notes about battery type, e.g. https://www.zigbee2mqtt.io/devices/WSDCGQ11LM.html.

**Comment by andrew-codechimp** [comment]
ZB2M does have useful information and a source I use to populate my batteries but being fairly unstructured it will be a manual approach.
ZHA differs with its manufacturer/model names so there will have to be some duplicates in the library to cope with both and any other integrations.
Working on a schema for the library at the moment, when I have something more solid I'll post here before release so we can start with a well populated library.

**Comment by dankarization** [comment]
Yeah, it should be a db first, populating it last.

**Comment by kaosmagix** [comment]
When using a list for Battery Type, you should also add a Number of Batteries as well. I know use the Type like "LR06/AAA (3)" 3 the number of batteries required.

**Comment by andrew-codechimp** [comment]
For those following this enhancement I am going to be adding the battery quantity within the db and then concatenating  it automatically with the type.
What do people prefer, please either thumb's up or heart this comment based on the options below to give me an idea.

👍 2x AAA
 ❤️ AAA (2)

**Comment by andrew-codechimp** [comment]
**Battery Library submissions are now open!**

I have a semi working version of the battery library with discovery so the schema is now set.
If you wish to contribute your devices please follow the instructions via the link below.
Please edit the library file that is in the main branch only.

https://github.com/andrew-codechimp/HA-Battery-Notes/tree/main#contributing-to-the-battery-library-coming-soon

**Comment by magicus** [comment]
I'd like to suggest that a standard terminology is prescribed. The AAA battery, for instance is also commonly called R03 (and sometimes UM-4), and apparently #7 in China.

Also, if we suspect that the same device might have different names depending on if e.g. ZHA or ZB2M is used, maybe it should be possible to add several model descriptions to a single entry..?

**Comment by andrew-codechimp** [comment]
> I'd like to suggest that a standard terminology is prescribed. The AAA battery, for instance is also commonly called R03 (and sometimes UM-4), and apparently #7 in China.
> 
> Also, if we suspect that the same device might have different names depending on if e.g. ZHA or ZB2M is used, maybe it should be possible to add several model descriptions to a single entry..?

Good call on naming, I have referenced the wikipedia article on most common naming in the instructions for submissions.
I may introduce aliases later if it becomes an issue, I didn't want to over complicate my schema for now.

**Comment by dankarization** [comment]
![image](https://github.com/andrew-codechimp/HA-Battery-Notes/assets/26330178/a859e962-22b0-42e6-9ba2-78a397b15963)
I get an error with every sensor and any name (or with no name)

**Comment by andrew-codechimp** [comment]
@dankarization  Did you restart Home Assistant?  Anything in the logs?

**Comment by dankarization** [comment]
1- Yes I did
2- nothing in logs (can I even turn on debug logging for an integration if I cant add this integration in the first place?)
3- yep

**Comment by kaosmagix** [comment]
I didn't have issues upgrading through Hacs. I removed one of the  integrations, re-added it and it recognized the battery type (so it seems to work with this limited testing)

**Comment by andrew-codechimp** [comment]
Thanks @kaosmagix 
@dankarization I'm wondering if it's an issue with the character set, would you mind replying with that device name so I can use it in my instance?  Also confirm the model/manufacturer of a device you are trying to add.
Sorry - english speaking only so excuse my ignorance.

**Comment by dankarization** [comment]
Name on the screenshot "Датчик движения под кроватью (Даня)" (Motion sensor (SNZB-03) by SONOFF), this one without russian characters give the same error "Indoor/Outdoor Meter 1659" (WoIOSensorTH by switchbot)

**Comment by DjBac** [comment]
Since I don't want to fill the issues space with unnecessary questions, how come the autodiscovery is not working?

**Comment by dankarization** [comment]
> Since I don't want to fill the issues space with unnecessary questions, how come the autodiscovery is not working?

not coded yet? :)

**Comment by DjBac** [comment]
I thought it was already there, quoting below:
"By default Battery Notes will automatically discover devices that it has in its library and create a notification to add a battery note."

**Comment by andrew-codechimp** [comment]
@DjBac It's coded and in the beta :)  Can you be a bit more specific
Have you restarted home assistant after installing the beta?
Any errors in the HA log view?
Is the device in the library?  
If you manually add by choosing the device and pressing Next does it auto populate the battery type?
Can you tell me what the device manufacturer/model is?

**Comment by dankarization** [comment]
> can I even turn on debug logging for an integration if I cant add this integration in the first place?

yes i can, and here are the logs for the sensor w/o russian carracrers in it's name

```
2023-12-13 13:15:09.317 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 227, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 233, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 31, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 149, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 63, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 177, in post
    return await super().post(request, flow_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 293, in async_configure
    result = await self._async_handle_step(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 389, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/battery_notes/config_flow.py", line 90, in async_step_user
    library = Library(self.hass)
              ^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/battery_notes/library.py", line 31, in __init__
    hass.data[DOMAIN][DOMAIN_CONFIG].get(CONF_LIBRARY, "library.json"),
    ~~~~~~~~~^^^^^^^^
KeyError: 'battery_notes'

```

**Comment by andrew-codechimp** [comment]
Thanks @dankarization that's told me where to look, not sure why yet and can't replicate but it's a good start!

**Comment by andrew-codechimp** [comment]
Finally tracked it down, it was all to do with new installs without any notes.
Please give beta version 1.1.1 a try and importantly add the following to your configuration.yaml

battery_notes:
  enable_autodiscovery: true

Thanks for your feedback on these issues!

**Comment by dankarization** [comment]
![image](https://github.com/andrew-codechimp/HA-Battery-Notes/assets/26330178/287e7c14-6ba1-4371-b8a8-b5b47f26b219)
![image](https://github.com/andrew-codechimp/HA-Battery-Notes/assets/26330178/fe1e8cb6-b7f7-49d5-8bdf-041d253c0cde)
Now everything works :)

**Comment by andrew-codechimp** [comment]
Thanks @dankarization for the quick feedback.  No wonder you were eager to test this with that many devices :)
I'll give it a few days and hopefully release it officially.

**Comment by kaosmagix** [comment]
I took the time to remove all manual Battery Notes, restarted with the auto discovery enabled and it found all 68 battery devices. Fantastic work @andrew-codechimp!

**Comment by andrew-codechimp** [comment]
Thanks @kaosmagix it's cool seeing it find so many devices automatically already, lets hope the library get's more contributions when I pluck up courage to release this fully in a few days.  It's really been interesting solving the problems, I'm learning more and more about integration dev because of the feedback I'm getting.

Replacement date is next on my list, but no promises when that will come.

**Comment by andrew-codechimp** [comment]
Version 1.1.3 has just been released fully with all battery library additions so marking this as closed.
