### ISSUE TITLE
How/Where to add battery type after installation

### ISSUE THREAD

**Issue by JAudi23** [andrew-codechimp/HA-Battery-Notes#31]
### System Health details

I can't seem to find this data in my installation

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/andrew-codechimp/ha-battery-notes/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

I've installed the integration through HACS, and see the Battery Notes card.
I have restarted my Home Assistant instance.
When I open a device with a battery (i.e. front door lock), I am unable to see anywhere to add the battery type.

### Reproduction steps

1. restarted HA
2. Navigate to HACS > Integrations > Battery Notes
3. Unable to see any option to add battery types
4. Navigate to a device with known batteries (4xAA)
5. Review diagnostic sensors, unable to see a sensor for battery type.
...

### Debug logs

```text
no logs found for this integration.
```

**Comment by andrew-codechimp** [comment]
On the "Configuration" -> "Integrations" -> "Battery Notes" screen click "Add Device", pick your device with a battery and add the battery type.
The battery type will then be displayed as a diagnostic sensor on the device.

**Comment by JAudi23** [comment]
Uggh, thanks.  I knew it was something simple.  I completely forgot to "add" in the integrations tab, after I had added the integration into HACS.

Thanks for the clarification.

**Comment by JAudi23** [comment]
Closing
