### ISSUE TITLE
Issue distinguishing the battery from the actual device

### ISSUE THREAD

**Issue by badnetmask** [andrew-codechimp/HA-Battery-Notes#365]
## System Information

version | core-2023.11.0
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
user | root
virtualenv | false
python_version | 3.11.6
os_name | Linux
os_version | 6.1.21-v8+
arch | aarch64
timezone | America/New_York
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4944
Installed Version | 1.33.0
Stage | running
Available Repositories | 1365
Downloaded Repositories | 8

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 5
views | 6
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | December 29, 2023 at 6:08 PM
-- | --
current_recorder_run | January 5, 2024 at 8:09 AM
estimated_db_size | 92.97 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

### Checklist

- [X] I have added `battery_notes:` to my configuration.yaml and restarted.
- [X] I have read the [FAQ's](https://github.com/andrew-codechimp/HA-Battery-Notes#faqs).
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/andrew-codechimp/ha-battery-notes/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Yesterday I submitted #323 to add a new device to be discovered. This morning I realized a small issue: the SOMFY integration (Overkiz) adds two devices in HASS per actual physical device. So, for each roller shade, I see one for the shade and one for the battery. However, both have the same manufacturer and model, so the battery notes discovery adds both of them. Is there a way to make the battery notes integration to discover only the battery itself?

The only possible way I can see to distinguish the devices is this:
* Roller -> Hardware: zigbee:SomfyRollerShadeComponent
* Battery -> Hardware: zigbee:SomfyConfigurationToolComponent

### Reproduction steps

1.
2.
3.
...

### Debug logs

```text
N/A
```

**Comment by andrew-codechimp** [comment]
Hi, there's no way to distinguish this as it's a non standard representation of a device.
I've updated the library to have a battery type of MANUAL for this device, this stops discovery and others changing it in future.
You can either restart HA to get the updated library and it won't be discovered or just Ignore the discovered one you don't want.
For these sort of devices you can always set the battery type manually which overrides anything the library may suggest.
