### ISSUE TITLE
Corresponding to its function: change 'PRESS' to 'SET'

### ISSUE THREAD

**Issue by Xander-V** [andrew-codechimp/HA-Battery-Notes#409]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/andrew-codechimp/ha-battery-notes/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement).

### Is your feature request related to a problem? Please describe.

The text "PRESS" is used as a button, and therefore I understand you choose press as the text, but it is a bit weird since it only describes the desired action from the user, and not the actual action taken after you press it.

### Describe the solution you'd like

The function this "button" has, is to set the date of the battery change to now(), so a text "SET" would be far more logical imho.

### Describe alternatives you've considered

None

### Additional context

When it says "SET", everybody would understand that this 'button' needs pressing to get to the desired action.

**Comment by andrew-codechimp** [comment]
The Press text is preset for all buttons within Home Assistant (other than Restart & Identify) and I can't provide my own text for this unfortunately.

**Comment by Xander-V** [comment]
Damn, I see. Well then I need to step it up a little and make a request at HA then to make this customizable then :)

Can you help point me to the place where I can find it in the code, so I can make a good request? They will probably react with "that was not the intended use for this function" but ok.

**Comment by andrew-codechimp** [comment]
The code for the button lives here, I think you'd have to cross reference to the UI code to see it hard coded, but here is where you'd have to have the option to specify it.
https://github.com/home-assistant/core/tree/dev/homeassistant/components/button
