### ISSUE TITLE
When setting the changing of a battery, give an option to change the date (pop-up)

### ISSUE THREAD

**Issue by Xander-V** [andrew-codechimp/HA-Battery-Notes#410]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/andrew-codechimp/ha-battery-notes/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement).

### Is your feature request related to a problem? Please describe.

Because this integration is so new for me, after changing a battery I sometimes forget to directly press "press" (which could imho better be renamed 'SET', see https://github.com/andrew-codechimp/HA-Battery-Notes/issues/409).

### Describe the solution you'd like

So after a few days I see the battery notes integration again somewhere and remember last week i replaced batteries from integration X. I now want to go to this entity and press 'SET' and be presented with a pop-up for the date/time. Of course the current date+time would be the default, but using the pop-up I would be able to easily change to last week or even earlier.

Since I used to write the date on the battery itself after replacing is (physically I mean) I would even be able to first set the date of the previous battery change to a date like 14 months ago, and then add the new date of today. The more date, the better the guess when to change it again will get.

![ef549986c861532566c83c9a5a11ad7d67f89c4a 1](https://github.com/andrew-codechimp/HA-Battery-Notes/assets/97856913/f08512d4-5a60-4f65-8c8c-95360a00594d)

### Describe alternatives you've considered

I've changed it manually using the developer tools/states/xxx_last_replaced, but that's quite a hassle. Also don't know if I need the change the date in the "button" as well, the two seem to be fully separated after the action has taken place?

### Additional context

To make guessing the next needed change even more reliable, the integration then also needs to remember previous times the batteries were changed, and since not all batteries of the same type are the same, also have the use register the make/specs of the battery used. Using an extra library it could then get data like mAH per type and calculate even better.

**Comment by andrew-codechimp** [comment]
The popup date/time isn't available for entities, it's been specifically coded within HA to only be used with the helpers which is a little annoying.  I cannot provide my own popup for this.

I am looking at adding an optional date on the service call but have some timezone issues to look into with that.

I would be cautious of updating the last_replaced date by the developer tools, I don't think this will survive a restart.
The button date/time is independent and just shows when the button was pressed, standard HA functionality so that does not need to be changed when editing manually.
