### ISSUE TITLE
Problems adding integration

### ISSUE THREAD

**Issue by DST73** [andrew-codechimp/HA-Battery-Notes#44]
## System Information

version | core-2023.12.1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.6
os_name | Linux
os_version | 6.1.63-haos
arch | x86_64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 3298
Installed Version | 1.33.0
Stage | running
Available Repositories | 1426
Downloaded Repositories | 87

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 11.2
-- | --
update_channel | stable
supervisor_version | supervisor-2023.11.6
agent_version | 1.6.0
docker_version | 24.0.7
disk_total | 121.3 GB
disk_used | 45.9 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Samba share (12.2.0), FTP (4.7.3), Terminal & SSH (9.8.1), Glances (0.20.0), AppDaemon (0.16.0), File editor (5.7.0), Home Assistant Google Drive Backup (0.112.1), Log Viewer (0.16.0), MariaDB (2.6.1), ZeroTier One (0.17.3), phpMyAdmin (0.9.0), Traccar (0.23.1), SQLite Web (4.0.0), Studio Code Server (5.14.2), Zigbee2MQTT (1.34.0-1), Advanced SSH & Web Terminal (17.0.0), Portainer (2.19.4), room-assistant (2.20.0), ESPHome (2023.11.6), Mosquitto broker (6.4.0), InfluxDB (4.8.0), EnOcean MQTT (dev) (0.1.28), Prometheus Node Exporter (0.7.0), Grocy (0.20.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 7
-- | --
resources | 53
views | 54
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 3. Dezember 2023 um 20:14
-- | --
current_recorder_run | 13. Dezember 2023 um 13:01
estimated_db_size | 4587.04 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/andrew-codechimp/ha-battery-notes/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

I have added you integration using HACS
When I add 
`battery_notes:
  enable_autodiscovery: true`
in my configuration.yaml and reboot HA I get an error that the integration does nocht support yaml.

### Reproduction steps

1. Add integration using HACS
2. add configuration.yaml
3. Reboot HA
...

### Debug logs

```text
No log needed
```

**Comment by andrew-codechimp** [comment]
Are you using the beta version of Battery Notes (version 1.1.1?)
If not you do not need to add that to the configuration.yaml

Also, enable_autodiscovery: true should be on a line below battery_notes and indented.

**Comment by DST73** [comment]
I am using 1.0.1 and the I have enable_autodiscovery: true in a second line. the text is in wrong format.
How do I achieve the autodiscovery? 
Thank you!

**Comment by andrew-codechimp** [comment]
autodiscovery was only released in beta yesterday, I've just added a comment to the readme to say this.

If you wish to try this version please go into HACS, select Battery Notes and in the top right menu choose Redownload, switch on Show Beta Versions and select the latest version (1.1.1 currently or the latest) 
Then restart HA

Otherwise remove the lines from the configuration.yaml for now until 1.1 is released fully.

**Comment by DST73** [comment]
Thank you. I have switched to 1.1.1. Now it is working
