### ISSUE TITLE
List of Xiaomi devices from Xiaomi Gateway 3 integration by Alexxit

### ISSUE THREAD

**Issue by to4ko** [andrew-codechimp/HA-Battery-Notes#472]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/andrew-codechimp/ha-battery-notes/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement).

### Is your feature request related to a problem? Please describe.

please add new device to library

### Describe the solution you'd like

        {
        "manufacturer": "Xiaomi",
        "model": "zigbee WSDCGQ01LM (lumi.sensor_ht)",
        "battery_type": "CR2032"
        },
        {
        "manufacturer": "Xiaomi",
        "model": "zigbee WXKG01LM (lumi.sensor_switch)",
        "battery_type": "CR2032"
        },
        {
        "manufacturer": "Aqara",
        "model": "zigbee WXKG11LM (lumi.remote.b1acn01)",
        "battery_type": "CR2032"
        },
        {
        "manufacturer": "Aqara",
        "model": "zigbee WXKG12LM (lumi.sensor_switch.aq3)",
        "battery_type": "CR2032"
        },
        {
        "manufacturer": "Xiaomi",
        "model": "zigbee WXKG01LM (lumi.sensor_switch)",
        "battery_type": "CR2032"
        },
        {
        "manufacturer": "Xiaomi",
        "model": "zigbee MCCGQ01LM (lumi.sensor_magnet)",
        "battery_type": "CR1632"
        },
        {
        "manufacturer": "Aqara",
        "model": "zigbee DJT11LM (lumi.vibration.aq1)",
        "battery_type": "CR2032"
        },
        {
        "manufacturer": "Xiaomi",
        "model": "zigbee GZCGQ01LM (lumi.sen_ill.mgl01)",
        "battery_type": "CR2032"
        },
        {
        "manufacturer": "Honeywell",
        "model": "zigbee JTYJ-GD-01LM/BW (lumi.sensor_smoke)",
        "battery_type": "CR123A",
        "battery_quantity": 2
        },
        {
        "manufacturer": "Aqara",
        "model": "zigbee MCCGQ11LM (lumi.sensor_magnet.aq2)",
        "battery_type": "CR1632"
        },
        {
        "manufacturer": "Xiaomi",
        "model": "zigbee RTCGQ01LM (lumi.sensor_motion)",
        "battery_type": "CR2450"
        },
        {
        "manufacturer": "Aqara",
        "model": "zigbee RTCGQ11LM (lumi.sensor_motion.aq2)",
        "battery_type": "CR2450"
        },
        {
        "manufacturer": "Aqara",
        "model": "zigbee WSDCGQ11LM (lumi.weather)",
        "battery_type": "CR2032"
        },
        {
        "manufacturer": "Aqara",
        "model": "zigbee WXCJKG11LM (lumi.remote.b286opcn01)",
        "battery_type": "CR2032"
        },
        {
        "manufacturer": "Aqara",
        "model": "zigbee WXCJKG12LM (lumi.remote.b486opcn01)",
        "battery_type": "CR2032"
        },
        {
        "manufacturer": "Aqara",
        "model": "zigbee WXKG02LM (lumi.sensor_86sw2)",
        "battery_type": "CR2032"
        },
        {
        "manufacturer": "Aqara",
        "model": "zigbee WXKG17LM (lumi.remote.acn004)",
        "battery_type": "CR2032"
        },
        {
        "manufacturer": "Xiaomi",
        "model": "ble CGD1",
        "battery_type": "AAA",
        "battery_quantity": 2
        },
        {
        "manufacturer": "Xiaomi",
        "model": "ble CGH1",
        "battery_type": "CR1632"
        },
        {
        "manufacturer": "Xiaomi",
        "model": "ble CGPR1",
        "battery_type": "CR2450",
        "battery_quantity": 2
        },
        {
        "manufacturer": "Xiaomi",
        "model": "ble LYWSD02MMC",
        "battery_type": "CR2032",
        "battery_quantity": 2
        },
        {
        "manufacturer": "Xiaomi",
        "model": "ble SJWS01LM",
        "battery_type": "CR2032"
        },
        {
        "manufacturer": "Yeelight",
        "model": "ble YLAI003",
        "battery_type": "CR2032"
        },

### Describe alternatives you've considered

NA

### Additional context

sorry for not adding via device addition form prepared json instead

**Comment by andrew-codechimp** [comment]
Thanks for the additions, that was a lot to add by a form but easier and quick for me to merge.
