### ISSUE TITLE
Device: philipshue_motion_outdoor_sensor_9290019758

### ISSUE THREAD

**Issue by uvjim** [andrew-codechimp/HA-Battery-Notes#60]
### Manufacturer

Philips

### Model

Hue motion outdoor sensor (9290019758)

### Battery Type

AA

### Battery Quantity

2

**Comment by andrew-codechimp** [comment]
Thanks, I had to add it manually, still beta issues with the form it seems :)

**Comment by uvjim** [comment]
Cheers. I had already forked the repo and then saw this template was available so thought I'd give it a whirl. 😁
