### ISSUE TITLE
Support binary_sensor battery device class

### ISSUE THREAD

**Issue by derekoharrow** [andrew-codechimp/HA-Battery-Notes#677]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/andrew-codechimp/ha-battery-notes/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement).

### Is your feature request related to a problem? Please describe.

Some devices use a binary sensor of device_class battery to indicate battery health - e.g. Tado TRVs

HA Battery Notes doesn't seem to work with these.

### Describe the solution you'd like

For devices using a battery device class binary_sensor, translate the on/off (Normal/Low) battery state to the Battery Low state for Battery Notes. The Battery Notes battery low binary sensor should match the device battery sensor.

### Describe alternatives you've considered

None

### Additional context

With Tado TRV devices as an example, they have a binary_sensor for battery state. HA Battery Notes doesn't seem to provide the battery low binary sensor for these devices. HA says "The entity is no longer being provided by the battery_notes integration..."

**Comment by andrew-codechimp** [comment]
Thanks for the detailed explanation, it's something I'll investigate although there are instances of multiple battery device class which will make it trickier to work through which is preferred.

The reason you have the  "The entity is no longer being provided by the battery_notes integration..." is a previous beta release incorrectly was picking up binary sensors and has been removed.  I'd suggest deleting the device in Battery Notes and re-adding it to tidy this up.

**Comment by andrew-codechimp** [comment]
See #681 for an idea that will solve both of these, closing this as it will be a longer term enhancement.
