### ISSUE TITLE
Silvercrest smart motion sensor

### ISSUE THREAD

**Issue by IgorSimic** [andrew-codechimp/HA-Battery-Notes#69]
### Manufacturer

Lidl

### Model

HG06335/HG07310

### Battery Type

CR123A

### Battery Quantity

1

**Comment by steff75** [comment]
HG06335 and HG07310 are 2 different motion sensors with different batteries, but zigbee2mqtt combines both under one listing.

HG06335 > **CR123A**
![HG06335](https://github.com/andrew-codechimp/HA-Battery-Notes/assets/19283026/574a7ca3-8f6a-49e9-a4a5-505b5b76dc80)

HG07310 > **2x AAA**
![HG07310](https://github.com/andrew-codechimp/HA-Battery-Notes/assets/19283026/51de4443-22e6-4cbc-8a40-04805736957f)

**Comment by andrew-codechimp** [comment]
Thanks for the update, I have removed this device from the library and you will have to add them manually depending on what you actually have.
