### ISSUE TITLE
Disable battery low

### ISSUE THREAD

**Issue by dankarization** [andrew-codechimp/HA-Battery-Notes#691]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/andrew-codechimp/ha-battery-notes/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement).

### Is your feature request related to a problem? Please describe.

New sensors are great, and I like how you add an option to disable some of them. Battery low sensor needs this disable feature even more than others :)

### Describe the solution you'd like

hide_battery_low configuration option

### Describe alternatives you've considered

-

### Additional context

-

**Comment by andrew-codechimp** [comment]
To help me understand the best way to handle this what the reason for needing it disabled?

**Comment by dankarization** [comment]
There are a lot of different ways to notify a user about low batteries already written on a lot of forums. It's even better to notify about it with actual battery percentage reading than just "low", because it can be "low" (for example, take 10% or less like in default configuration) for a few weeks. And setting this parameter too low is unrelaible- some sensors can die even on 20-30%, especially if placed in cold environment.
Secondly, this is a binary sensor, being the easiest to auto populate dashboards with with some simple filters. So I guess for a lot of people there will be a need to modify these filters or disable this sensor manually, if they don't want to see these new readings in their dashboard.
And last but not least- that's just a new entity you get to fill your precious space in database, even if you don't need it (idk about other people here, but mine is already 4GB after just a few years of using my latest HA install and trying to disable everything I have no need to).
Generally, since there's already a way to disable some sensors, created by your integration, it's good to have selection to enable or disable not only some, but every single one of them. That also applies to battery+ one and future ones 🫡

**Comment by andrew-codechimp** [comment]
The reason battery replaced got a disable option was that the button could change the state, and if you weren't using it and accidentally pressed the button you were stuck with a state.  This was a very unusual case that I saw the need to disable.
With the battery low boolean you can override this per device for those that last a long time very low or those that need changing at a higher level, saving you writing specific filters to handle this.
With sensors also appearing in attributes and relating to events handling this for every single option will make it very difficult to test/maintain. No other integration offers to disable arbitrary sensors.
I will give options like this for anything that can cause undesired effects like battery replaced but the regular sensors I'll not give this option.
Sorry, but I have to draw the line somewhere between flexibility and tying myself in knots supporting/maintaining this.
