### ISSUE TITLE
Use a text box with number format to enter quantity in config flow

### ISSUE THREAD

**Issue by uvjim** [andrew-codechimp/HA-Battery-Notes#77]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/andrew-codechimp/ha-battery-notes/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

The config flow contains a label to "optionally" enter the number of batteries a device takes. It's possible to enter this in a format that doesn't like up with that used by the sensor when completed via the library. This creates an inconsistent view in the UI.

### Describe the solution you'd like

A textbox in the config flow to allow entry of the quantity (defaulting to 1). This would allow processing and for atting the same way as those populated by the library.

### Describe alternatives you've considered

Defining the format of entry in the label stating that it is optional.

### Additional context

The entry screen in the config flow.

![image](https://github.com/andrew-codechimp/HA-Battery-Notes/assets/8431065/d43dfe52-2225-4d34-896d-0dd0ad8788ea)

Badly formatted battery type with quantity.
![image](https://github.com/andrew-codechimp/HA-Battery-Notes/assets/8431065/1f3b370c-94e8-45bb-8dfb-4c33c15ce34b)

Correctly formatted battery type from library.
![image](https://github.com/andrew-codechimp/HA-Battery-Notes/assets/8431065/68a4c75b-336b-4ba4-9246-743e92881f32)

**Comment by andrew-codechimp** [comment]
I like the quantity input idea but as I'm in the code today I've quickly adding a hint until I can work on it more.

**Comment by tplas** [comment]
My preference would be to NOT enforce any input formatting; I very much like the ability to free-format absolutely anything that's meaningful to me that concerns notes about the device batteries.

**Comment by andrew-codechimp** [comment]
I have a migration plan to fully achieve this which I'll be rolling out in the next few weeks, see #421
