### ISSUE TITLE
Battery Low binary sensor

### ISSUE THREAD

**Issue by hellcry37** [andrew-codechimp/HA-Battery-Notes#786]
### System Health details

not needed

### Checklist

- [X] I have added `battery_notes:` to my configuration.yaml and restarted.
- [X] I have read the [FAQ's](https://andrew-codechimp.github.io/HA-Battery-Notes/faq).
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/andrew-codechimp/ha-battery-notes/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

As you can imagine some devices already have a binary_sensor.name_battery_low and when this cool integration adds his own _battery_low it comes up as binary_sensor.name_battery_low_2

Can we change this sensor to another name by default?
binary_sensor.name_battery_plus_low
binary_sensor.name_battery_low_plus

Something that will not interfere with sensors already present.

Thanks in advance.

### Reproduction steps

1. add battery plus for any device that has battery_low reported already
...

### Debug logs

```text
not needed
```

### Diagnostics dump

not needed

**Comment by andrew-codechimp** [comment]
I'm checking on the impact of this but put it on my list.

**Comment by andrew-codechimp** [comment]
A beta 2.0.10 has just been released that fixes this, for new battery notes devices only, you will have to manually rename old ones or delete the battery notes and re-create.
