### ISSUE TITLE
Add standard note for non-standard rechargeable batteries and nonstandard irreplaceable batteries

### ISSUE THREAD

**Issue by kaosmagix** [andrew-codechimp/HA-Battery-Notes#80]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/andrew-codechimp/ha-battery-notes/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

For consistency add standard battery types for non-standard battery rechargeable devices like Ring doorbell and non-standard irreplaceable batteries like smoke detectors to allow all battery devices to auto discover battery notes.

Functionality is already there it is more a question on defining a "standard" battery type label for these types. This to add them in a consistent way to the library. 

### Describe the solution you'd like

new labels:
- Non-standard rechargeable battery
- Irreplaceable battery 

### Describe alternatives you've considered

Manual entry without auto discovery

### Additional context

I like all my battery devices linked where possible as that provides a way to create a singe list of batteries and near future replacements

**Comment by andrew-codechimp** [comment]
I think you'd want to keep these fairly short so they don't crop/wrap in small views.

Maybe just Rechargeable and Irreplaceable ?

**Comment by kaosmagix** [comment]
The short label Sounds good. It is just something you need to add to the documentation and the issue form to create consistency in database entries

**Comment by kaosmagix** [comment]
Added a few devices with rechargeable batteries (Ring doorbell) and irreplaceable batteries (Heiman smoke sensor)

**Comment by codyc1515** [comment]
Could just be Replaceable = Yes / No

**Comment by WendelFelius** [comment]
This is interesting. However how would that work when the power source could be different for a device? For example the Hunter Douglas Duette has a configurable power source; either a battery wand (12 x AA), Rechargeable or Hardwired. 

![Screenshot 2023-12-18 om 09 31 02@2x](https://github.com/andrew-codechimp/HA-Battery-Notes/assets/8288091/4ae789bd-5c32-4307-b3c3-f33f747c7367)

**Comment by andrew-codechimp** [comment]
I don't think we're going to cover every option here and I'd rather not increase the schema for very unusual cases.
I'll go with Rechargeable/Irreplaceable as options and add to readme.
There will always be the option to overwrite the library value.

**Comment by codyc1515** [comment]
How is hard wired relevant to this? There would be no relevance to a battery in that case.

**Comment by andrew-codechimp** [comment]
I see @WendelFelius point, if it's in the library as Rechargeable but you happen to have your device Hard Wired the library will suggest the wrong value.  Why I'm always going to get you to confirm the battery type on discovered items so you can make a sensible choice for your own use.
As an example, where I have AA rechargeable's in use I'll put 2x AA(r) for my own purposes.
