### ISSUE TITLE
entity_id's don't take device name but manufacturer/model name

### ISSUE THREAD

**Issue by jossiee** [andrew-codechimp/HA-Battery-Notes#894]
## System Information

version | core-2024.1.6
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.6
os_name | Linux
os_version | 6.1.63-haos-raspi
arch | aarch64
timezone | Europe/Amsterdam
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.34.0
Stage | running
Available Repositories | 1392
Downloaded Repositories | 53

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 3 februari 2025 om 01:00
relayer_connected | true
relayer_region | eu-central-1
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | true
remote_server | eu-central-1-2.ui.nabu.casa
certificate_status | ready
instance_id | 304302a3e9bd4d598344ab67c4a352a2
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 11.4
-- | --
update_channel | stable
supervisor_version | supervisor-2023.12.1
agent_version | 1.6.0
docker_version | 24.0.7
disk_total | 219.4 GB
disk_used | 23.9 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Duck DNS (1.15.0), Mosquitto broker (6.4.0), File editor (5.7.0), Check Home Assistant configuration (3.11.0), Advanced SSH & Web Terminal (17.1.0), Samba Backup (5.2.0), Studio Code Server (5.15.0), WireGuard (0.10.2), Samba share (12.2.0), SQLite Web (4.1.0), Node-RED (17.0.3), ESPHome (2023.12.9), eufy-security-ws (1.7.1), RTSP Simple Server Add-on (v0.17.6), Uptime Kuma (0.12.0), AdGuard Home (5.0.2), Silicon Labs Flasher (0.2.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 7
-- | --
resources | 36
views | 28
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 5 januari 2024 om 11:01
-- | --
current_recorder_run | 4 februari 2024 om 22:06
estimated_db_size | 2466.05 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

<details><summary>Sonoff</summary>

version | 3.5.4 (a4a8c5f)
-- | --
cloud_online | 2 / 2
local_online | 2 / 2

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Checklist

- [X] I have added `battery_notes:` to my configuration.yaml and restarted.
- [X] I have read the [FAQ's](https://andrew-codechimp.github.io/HA-Battery-Notes/faq).
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/andrew-codechimp/ha-battery-notes/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

The entity's that get added do not all take on the proper name of the device. only _battery_low takes on device name the rest takes on the manufacturer and model name

a example.
![image](https://github.com/andrew-codechimp/HA-Battery-Notes/assets/8819339/f8a54071-90ae-4ef4-9a84-2e8089eaccf8)

debug:
[home-assistant_battery_notes_2024-02-04T22-24-19.993Z.log](https://github.com/andrew-codechimp/HA-Battery-Notes/files/14158731/home-assistant_battery_notes_2024-02-04T22-24-19.993Z.log)

maybe this is not a bug but does feel like it.

### Reproduction steps

just add device and see

### Debug logs

```text
file to big see uploaded .log.
```

**Comment by andrew-codechimp** [comment]
Can you confirm if other devices are doing this as well?
Also - can you delete this device from battery notes (integrations/battery notes/find device, click on the dots and delete) then re-add it?

**Comment by jossiee** [comment]
All devices have the same behavior.
In the first debug log you should see that i manually added a new device (near the end off the log file) called 3_voudig_schakelaar.

i tried removing and re-adding a device still the same result.

**Comment by jossiee** [comment]
> I have identified the issue and am testing a fix. Hopefully it will be included in a release later this week.
> 
> For existing items, if you go into the device, rename the device temporarily, then rename it back, selecting Rename Entity ID's it will create the correct entity_id's.

unfortunatly it does not solve it. only the one that is already okay gets renamed

renamed
![image](https://github.com/andrew-codechimp/HA-Battery-Notes/assets/8819339/3415add1-9e24-4ce7-83ac-fa97513e170b)

back to old name
![image](https://github.com/andrew-codechimp/HA-Battery-Notes/assets/8819339/1f37ab2a-52ea-4caf-870a-625996359f5a)

i will wait for the fix and get back to you! thanks for now!

**Comment by jossiee** [comment]
![image](https://github.com/andrew-codechimp/HA-Battery-Notes/assets/8819339/87feb47e-deca-43dc-b5dd-d743da05a9ef)

running 2.0.10 removed devices and re add them now it is fixed! thank you!

**Comment by andrew-codechimp** [comment]
Thanks for the very quick testing of this.
