### ISSUE TITLE
Show only battery-holding devices in device-dropdown when creating a new Battery-Note

### ISSUE THREAD

**Issue by marcelhoogantink** [andrew-codechimp/HA-Battery-Notes#93]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/andrew-codechimp/ha-battery-notes/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

The list of devices the dropdown for devices when creating a new battery-note contains all available devices. This is/can be a very long list. Most many devices do not have a battery and are unnecessary in the list.

### Describe the solution you'd like

Fill the devices list with a filter that only includes devices which has a battery

### Describe alternatives you've considered

NA

### Additional context

NA

**Comment by andrew-codechimp** [comment]
I did look at this but couldn't seem to find a way to filter devices to those with a certain entity

https://github.com/andrew-codechimp/HA-Battery-Notes/blob/03a46e256b3f18aee5dbe23193754fa62bdc3fcd/custom_components/battery_notes/config_flow.py#L38

**Comment by uvjim** [comment]
Have a gander [here](https://www.home-assistant.io/docs/blueprint/selectors/#example-device-selector)... The example shows how to look for devices that provide a battery sensor.

**Comment by uvjim** [comment]
I'm not in a position to test but I think this should work (or at least get you close)

You will need to add the following to the block of imports...

```python
from homeassistant.const import Platform
from homeassistant.components.sensor import SensorDeviceClass
```

This would be your device selector
```python
        vol.Required(CONF_DEVICE_ID): selector.DeviceSelector(
            config=selector.DeviceFilterSelectorConfig(
                entity=[
                    selector.EntitySelectorConfig(
                        selector.EntityFilterSelectorConfig(
                            domain=Platform.SENSOR,
                            device_class=SensorDeviceClass.BATTERY,
                        )
                    )
                ]
            )
```

**Comment by andrew-codechimp** [comment]
Thanks, just tested that and it seems to work.  A lot more testing and a config option to override this before I release.

For dev I'm always adding a PP3 battery to the Sun to save adding physical devices to my dev instance :)

**Comment by uvjim** [comment]
There's a possibility that you may need to add an entity filter to check for the binary_sensor domain as well.  I know the blink integration uses that domain for battery sensors as it can only report on good/bad state.

The `entity` parameter is a list so you should be able to add that in easily enough.  I can't recall if the selector is then matching against "one of" or "all".  It would make sense to be "one of" though.

**Comment by andrew-codechimp** [comment]
@uvjim Pleased to say the selector is "one of", even though I've not got binary_sensor batteries I'm not losing my sensor batteries by adding them.  My testing will continue but looks like this is going to work.

**Comment by uvjim** [comment]
@andrew-codechimp that's good then. Glad I could be of some help. Keep up the learning and good work.
