### ISSUE TITLE
Device: HEIMAN - Smart_motion_sensor_HS3MS_by_HEIMAN

### ISSUE THREAD

**Issue by Kobberholm** [andrew-codechimp/HA-Battery-Notes#941]
### Manufacturer

HEIMAN

### Model

Smart motion sensor (HS3MS) by HEIMAN

### Battery Type

CR123A

### Battery Quantity

1

**Comment by Kobberholm** [comment]
This device is just called "Smart motion sensor (HS3MS)". The "by HEIMANN" is added by HA on the device info page and I shouldn't have included that in the name.

**Comment by andrew-codechimp** [comment]
Thanks for the update, I've made that change
