### ISSUE TITLE
New Language

### ISSUE THREAD

**Issue by Dis90** [andrew-codechimp/HA-Battery-Notes#967]
### Language

Finnish

**Comment by andrew-codechimp** [comment]
Thanks for volunteering, you're the first to use this new method.  
I've just added Finnish so you should be able to add translations now here
https://crowdin.com/project/battery-notes

**Comment by andrew-codechimp** [comment]
Thanks for the translation, I have merged this in and will include it in the next release.
#969

**Comment by Dis90** [comment]
Thanks. I just made update to one line.

**Comment by andrew-codechimp** [comment]
Thanks that's been merged
