### ISSUE TITLE
Timestamp is incorrect for new attribute battery_last_reported

### ISSUE THREAD

**Issue by danielbrunt57** [andrew-codechimp/HA-Battery-Notes#970]
### System Health details

n/a

### Checklist

- [X] I have added `battery_notes:` to my configuration.yaml and restarted.
- [X] I have read the [FAQ's](https://andrew-codechimp.github.io/HA-Battery-Notes/faq).
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/andrew-codechimp/ha-battery-notes/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

The timestamp is wrong as the UI displays the datetime in the future.
It needs `+00:00` appended to it (the same format as `battery_last_replaced` )
```
state_class: measurement
battery_quantity: 4
battery_type: AAA
battery_type_and_quantity: 4x AAA
battery_low: false
battery_low_threshold: 15
battery_last_reported: "2024-02-12T09:35:52.050106"
battery_last_reported_level: "63.0"
battery_last_replaced: "2024-01-18T12:24:29.863292+00:00"
unit_of_measurement: "%"
device_class: battery
friendly_name: Landing 1 Sensor
hide_attributes:
  - templates
templates:
  icon_color: >
    var r = Math.min(255, Math.round(510 - 5.10 * Number(state))); var g =
    Math.min(255, Math.round(5.10 * Number(state))); var h = r * 0x10000 + g *
    0x100; return '#' + ('000000' + h.toString(16)).slice(-6);
icon_color: "#bdff00"
```
should be:
```
state_class: measurement
battery_quantity: 4
battery_type: AAA
battery_type_and_quantity: 4x AAA
battery_low: false
battery_low_threshold: 15
battery_last_reported: "2024-02-12T09:35:52.050106+00:00"
battery_last_reported_level: "63.0"
battery_last_replaced: "2024-01-18T12:24:29.863292+00:00"
unit_of_measurement: "%"
device_class: battery
friendly_name: Landing 1 Sensor
hide_attributes:
  - templates
templates:
  icon_color: >
    var r = Math.min(255, Math.round(510 - 5.10 * Number(state))); var g =
    Math.min(255, Math.round(5.10 * Number(state))); var h = r * 0x10000 + g *
    0x100; return '#' + ('000000' + h.toString(16)).slice(-6);
icon_color: "#bdff00"
```

### Reproduction steps

n/r

### Diagnostics dump

![image](https://github.com/andrew-codechimp/HA-Battery-Notes/assets/49846893/b8a56d2b-bad8-4488-a2b4-5e3a09ab3a1d)

![image](https://github.com/andrew-codechimp/HA-Battery-Notes/assets/49846893/e5b3d8e5-91e8-42fc-a01c-5daee76bedf9)

**Comment by andrew-codechimp** [comment]
Thanks for spotting this, the trouble with living in the UK is you don't spot these for half the year!
Merged a fix and will be in the next release.

**Comment by danielbrunt57** [comment]
Understood, since UK **_is_** UTC +00:00!
