### ISSUE TITLE
Changing the friendly name of battery_notes_plus sensor reverts to original after a system restart

### ISSUE THREAD

**Issue by simenopsahl** [andrew-codechimp/HA-Battery-Notes#988]
## System Information

version | core-2024.2.1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.1
os_name | Linux
os_version | 6.1.63-haos-raspi
arch | aarch64
timezone | Europe/Oslo
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 3470
Installed Version | 1.34.0
Stage | running
Available Repositories | 1465
Downloaded Repositories | 135

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 25. august 2024 kl. 02:00
relayer_connected | true
relayer_region | eu-central-1
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | true
remote_server | eu-central-1-4.ui.nabu.casa
certificate_status | ready
instance_id | 7156c9fe7761430b8e0c2d15f04c4f73
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 11.5
-- | --
update_channel | stable
supervisor_version | supervisor-2024.01.1
agent_version | 1.6.0
docker_version | 24.0.7
disk_total | 109.3 GB
disk_used | 47.9 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Samba share (12.3.0), AirCast (4.2.0), Mosquitto broker (6.4.0), AppDaemon (0.16.4), Studio Code Server (5.15.0), Advanced SSH & Web Terminal (17.1.0), MariaDB (2.6.1), ArgonOne Active Linear Cooling (30a), InfluxDB (5.0.0), Grafana (9.1.3), Home Assistant Google Drive Backup (0.112.1), Glances (0.21.0), Frigate Proxy (1.4), ESPHome (2023.12.9), HassOS I2C Configurator (0.13a), Zigbee2MQTT Proxy (0.2.0), Network UPS Tools (0.13.0), Fusion (2024.2.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 7
-- | --
resources | 92
views | 46
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 15. desember 2023 kl. 16:25
-- | --
current_recorder_run | 12. februar 2024 kl. 22:17
estimated_db_size | 14783.83 MiB
database_engine | mysql
database_version | 10.6.12

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Checklist

- [X] I have added `battery_notes:` to my configuration.yaml and restarted.
- [X] I have read the [FAQ's](https://andrew-codechimp.github.io/HA-Battery-Notes/faq).
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/andrew-codechimp/ha-battery-notes/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Most of my sensors are named like `1fl, Bathroom Leak Washer Battery CR2032` (from before this integration was available), but I want to rename the battery_notes_plus sensor to just `Leak: Washer` for sorting in a auto populated battery entities card. After a system reboot, the names revert back to the original name taken from the device e.g `1fl, Bathroom Leak Washer Battery CR2032+`

I noticed the BLE plant sensor and pet collar tracker names do stay changed, but the ~80 or so sensors from (Zigbee2)MQTT all revert to the default name

### Reproduction steps

1. Give new friendly name to sensors
2. Some other updates on HACS
3. Restart HomeAssistant to enable new updates
4. Sensor names have reverted back to the default name

**Comment by andrew-codechimp** [comment]
Just tested and can confirm it happens on Z2M but not on some of my other devices.
I'll look into it but it's a strange one.

**Comment by andrew-codechimp** [comment]
Found it and put a fix in for next release.
