### ISSUE TITLE
Reload library.json without HA restart

### ISSUE THREAD

**Issue by IgorSimic** [andrew-codechimp/HA-Battery-Notes#99]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/andrew-codechimp/ha-battery-notes/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

Data base of devices (library.json) grows very fast so releases comes often and every time HA need to be restarted.

### Describe the solution you'd like

Wonder if will be possible to reload library.json somehow, without need to restart HA.

### Describe alternatives you've considered

Maybee some kind of service which will load library.json directly from github?

### Additional context

no

**Comment by andrew-codechimp** [comment]
I am also aware of the number of releases at the moment.
I'm hoping we'll have the large majority covered soon and I will reduce releases to weekly at most but if that's not the case it's something I'll investigate.

**Comment by andrew-codechimp** [comment]
With release 1.2.0 this has now been added, the library will automatically be updated approx every 24 hours.
